/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.usuario;

import Externos.CambiarPanel;
import Objetos.Inventario;
import Objetos.ObAn;
import Vista.Plantilla;

/**
 *
 * @author PC
 */
public class Catalogo1 extends javax.swing.JPanel {

    /**
     * Creates new form UserItsprISC
     */
    Inventario inventario;
    public Catalogo1() {
        initComponents();
        
        labelCarrera.setText("Ingenieria en sistemas");
        ObAn.colocarFoto(labelCamisaMC, 3);
        ObAn.colocarFoto(labelCamisaML, 9);
        ObAn.colocarFoto(labelPlayera, 15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelCarrera = new javax.swing.JLabel();
        labelPlayera = new javax.swing.JLabel();
        labelCamisaMC = new javax.swing.JLabel();
        labelCamisaML = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 230, 230));

        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 230, 230));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 230, 230));

        labelCarrera.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        labelCarrera.setForeground(new java.awt.Color(196, 196, 196));
        labelCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(labelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 90));
        add(labelPlayera, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 210, 220));
        add(labelCamisaMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 210, 220));
        add(labelCamisaML, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 210, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Catalogo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        proceso("Camisa manga larga");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        proceso("Camisa manga corta");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        proceso("Playera");
    }//GEN-LAST:event_jButton3ActionPerformed

       public void proceso(String tipoCamisa){
          
            ObAn.inventarioUsuario.setTipo(tipoCamisa);
            ObAn.visualizarProducto.inventario = new SQL.Conexion().obtenerStock(ObAn.inventarioUsuario.getEscuela(),ObAn.inventarioUsuario.getCarrera() , ObAn.inventarioUsuario.getTipo(), ObAn.inventarioUsuario.getSexo(),ObAn.inventarioUsuario.getTalla());
            ObAn.mostrarInformacionUsuario(ObAn.visualizarProducto.inventario, 1);
            new CambiarPanel(Plantilla.jPanel1, ObAn.visualizarProducto);
        
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel labelCamisaMC;
    public javax.swing.JLabel labelCamisaML;
    public javax.swing.JLabel labelCarrera;
    public javax.swing.JLabel labelPlayera;
    // End of variables declaration//GEN-END:variables
}
