/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.usuario;

import Externos.CambiarPanel;
import Objetos.Carrito;
import Objetos.Inventario;
import Objetos.ObAn;
import static Objetos.ObAn.*;
import Vista.Plantilla;
import java.awt.Image;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pahcual
 */
public class User extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    int contadorClick = 0;
    public ArrayList<Carrito> carrito = new ArrayList<>();

    public User() {
        initComponents();
        botonAtras.setVisible(false);
        //ObAn.inventario.setEscuela("ITSPR");
        //ObAn.inventario.setCarrera("Ing. en sistemas");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bolsa-1.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bolsa-2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 635, 88, 86));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComprasAMayoreo-1.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComprasAMayoreo-2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 645, 367, 75));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carrito-1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carrito-2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 640, 81, 78));

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png"))); // NOI18N
        botonAtras.setBorder(null);
        botonAtras.setBorderPainted(false);
        botonAtras.setContentAreaFilled(false);
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.setFocusPainted(false);
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 60));

        botonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonSiguiente.png"))); // NOI18N
        botonSiguiente.setBorder(null);
        botonSiguiente.setBorderPainted(false);
        botonSiguiente.setContentAreaFilled(false);
        botonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSiguiente.setFocusPainted(false);
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 160, 60, 60));

        contenedor.setLayout(new java.awt.BorderLayout());
        add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 219, 1270, 386));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UV-1 (usuario).png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UV-2 (usuario).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 118, 194, 73));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ITSPR-1 (usuario).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ITSPR-2 (usuario).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 118, 194, 73));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 4, 84, 85));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TEPEYAC-1 (usuario).png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TEPEYAC-2 (usuario).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 118, 194, 73));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/COBAEV-1 (usuario).png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/COBAEV-2 (usuario).png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 117, 194, 73));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonPregunta-1.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonPregunta-2.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 635, 88, 86));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UserGeneral_1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        contadorClick--;
        identificarProcesoCorrespondiente(contadorClick);

    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        // TODO add your handling code here:
        contadorClick++;
        identificarProcesoCorrespondiente(contadorClick);

    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ObAn.panelCarrito.acumuladorTotal = 0;
        ObAn.panelCarrito.mostrarCarrito();
        new CambiarPanel(Plantilla.jPanel1, ObAn.panelCarrito);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(Plantilla.jPanel1, ObAn.contactanos);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ObAn.inventarioUsuario.setEscuela("ITSPR");
        ObAn.inventarioUsuario.setCarrera("Ing. en sistemas");
        visualizarBotonesNavegacion(true);
        new CambiarPanel(ObAn.user.contenedor, ObAn.catalogo1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ObAn.inventarioUsuario.setEscuela("UV");
        visualizarBotonesNavegacion(false);
        new CambiarPanel(ObAn.user.contenedor, ObAn.catalogoUV);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        //Aqui podemos ahorrar codigo y utilizar el metodo mostrarDatosMostrarProducto() que se encuentra en ObAn.
        //Solo hay que hacer que reciba como parametros un jpanel y un objeto inventario, creo.
        ObAn.inventarioUsuario.setEscuela("TEPEYAC");
        ObAn.inventarioUsuario.setTipo("Chaleco");
        ObAn.inventarioUsuario.setCarrera("General");
        ObAn.visualizarProducto.inventario = new SQL.Conexion().obtenerStock(ObAn.inventarioUsuario.getEscuela(), ObAn.inventarioUsuario.getCarrera(), ObAn.inventarioUsuario.getTipo(), ObAn.inventarioUsuario.getSexo(), ObAn.inventarioUsuario.getTalla());
        ObAn.mostrarInformacionUsuario(ObAn.visualizarProducto.inventario, 1);
        new CambiarPanel(Plantilla.jPanel1, ObAn.visualizarProducto);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ObAn.inventarioUsuario.setEscuela("COBAEV");
        ObAn.inventarioUsuario.setTipo("Playera");
        ObAn.inventarioUsuario.setCarrera("General");
        ObAn.visualizarProducto.inventario = new SQL.Conexion().obtenerStock(ObAn.inventarioUsuario.getEscuela(), ObAn.inventarioUsuario.getCarrera(), ObAn.inventarioUsuario.getTipo(), ObAn.inventarioUsuario.getSexo(), ObAn.inventarioUsuario.getTalla());
        ObAn.mostrarInformacionUsuario(ObAn.visualizarProducto.inventario, 1);
        new CambiarPanel(Plantilla.jPanel1, ObAn.visualizarProducto);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //Regresamos al login.
        
        //Limpiamos el carrito, digo, no lo ha pagado, seas mamon. xd
        carrito.clear();
        
        //Cambiamos de panel (al login obviamente).
        new CambiarPanel(Plantilla.jPanel1, ObAn.login);
        
        //Detras de camaras colocamos el panel "catalogo1" en el contenedor que tengo dentro del panel "user".
        new CambiarPanel(ObAn.user.contenedor, ObAn.catalogo1);
        
        //Coloco la flechita hacia adelante como true, osea visible para los q no saben inglish.
        ObAn.user.botonSiguiente.setVisible(true);
        //Coloco la flechita hasta atras invisible
        ObAn.user.botonAtras.setVisible(false);
        
        //El contador lo reinicio
        ObAn.user.contadorClick = 0;
        
        //Establezco como valores predeterminados lo siguiente...
        ObAn.inventarioUsuario.setEscuela("ITSPR");
        ObAn.inventarioUsuario.setCarrera("Ing. en sistemas");
        ObAn.inventarioUsuario.setTipo("");
        
        //Coloco las fotos dentro del catalogo1 y a cada label correspóndiente.
        ObAn.colocarFoto(ObAn.catalogo1.labelCamisaMC, 3);
        ObAn.colocarFoto(ObAn.catalogo1.labelCamisaML, 9);
        ObAn.colocarFoto(ObAn.catalogo1.labelPlayera, 15);
        
        //Cambiamos el color de los iconos junto con el RolloverIcon para mas placer.
        ObAn.login.cambiarIconMinimizar("src/Imagenes/Minimizar-1 (verdeblanco).png", "src/Imagenes/Minimizar-2 (verdeblanco).png");
        ObAn.login.cambiarIconCerrar("src/Imagenes/Cerrar-1 (verdeblanco).png", "src/Imagenes/Cerrar-2 (verdeblanco).png");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ObAn.misCompras.mostrarMisCompras();
        new CambiarPanel(Plantilla.jPanel1, ObAn.misCompras);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(ObAn.vd2.jPanel1, ObAn.preguntasFrecuentes);
            ObAn.vd2.setVisible(true);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void identificarProcesoCorrespondiente(int numero) {
        switch (contadorClick) {
            case 0:
                botonAtras.setVisible(false);
                ObAn.inventarioUsuario.setCarrera("Ing. en sistemas");
                ObAn.catalogo2.labelCarrera.setText("Ingenieria en sistemas");
                colocarFoto(ObAn.catalogo2.labelCamisaMC, 3);
                colocarFoto(ObAn.catalogo2.labelCamisaML, 9);
                colocarFoto(ObAn.catalogo2.labelPlayera, 15);
                ObAn.animacionCatalogo(ObAn.catalogo1, ObAn.catalogo2);
                break;

            case 1:
                botonAtras.setVisible(true);
                ObAn.inventarioUsuario.setCarrera("Gestion empresarial");
                ObAn.catalogo1.labelCarrera.setText(inventarioUsuario.getCarrera());

                colocarFoto(ObAn.catalogo1.labelCamisaMC, 21);

                colocarFoto(ObAn.catalogo1.labelCamisaML, 27);
                colocarFoto(ObAn.catalogo1.labelPlayera, 33);
                ObAn.animacionCatalogo(ObAn.catalogo2, ObAn.catalogo1);
                break;

            case 2:
                ObAn.inventarioUsuario.setCarrera("Electromecanica");
                ObAn.catalogo2.labelCarrera.setText(inventarioUsuario.getCarrera());
                colocarFoto(ObAn.catalogo2.labelCamisaMC, 39);
                colocarFoto(ObAn.catalogo2.labelCamisaML, 45);
                colocarFoto(ObAn.catalogo2.labelPlayera, 51);
                ObAn.animacionCatalogo(ObAn.catalogo1, ObAn.catalogo2);
                break;
            case 3:
                ObAn.inventarioUsuario.setCarrera("Electronica");
                ObAn.catalogo1.labelCarrera.setText(inventarioUsuario.getCarrera());
                colocarFoto(ObAn.catalogo1.labelCamisaMC, 57);
                colocarFoto(ObAn.catalogo1.labelCamisaML, 63);
                colocarFoto(ObAn.catalogo1.labelPlayera, 69);
                ObAn.animacionCatalogo(ObAn.catalogo2, ObAn.catalogo1);
                break;

            case 4:
                ObAn.inventarioUsuario.setCarrera("Industrial");
                ObAn.catalogo2.labelCarrera.setText(inventarioUsuario.getCarrera());
                colocarFoto(ObAn.catalogo2.labelCamisaMC, 75);
                colocarFoto(ObAn.catalogo2.labelCamisaML, 81);
                colocarFoto(ObAn.catalogo2.labelPlayera, 87);
                ObAn.animacionCatalogo(ObAn.catalogo1, ObAn.catalogo2);
                break;

            case 5:
                ObAn.inventarioUsuario.setCarrera("Mecatronica");
                ObAn.catalogo1.labelCarrera.setText(inventarioUsuario.getCarrera());
                colocarFoto(ObAn.catalogo1.labelCamisaMC, 93);
                colocarFoto(ObAn.catalogo1.labelCamisaML, 99);
                colocarFoto(ObAn.catalogo1.labelPlayera, 105);
                ObAn.animacionCatalogo(ObAn.catalogo2, ObAn.catalogo1);
                break;

            case 6:
                ObAn.inventarioUsuario.setCarrera("Nanotecnologia");
                ObAn.catalogo2.labelCarrera.setText(inventarioUsuario.getCarrera());
                colocarFoto(ObAn.catalogo2.labelCamisaMC, 111);
                colocarFoto(ObAn.catalogo2.labelCamisaML, 117);
                colocarFoto(ObAn.catalogo2.labelPlayera, 123);
                ObAn.animacionCatalogo(ObAn.catalogo1, ObAn.catalogo2);
                break;

            case 7:
                botonSiguiente.setVisible(true);
                ObAn.inventarioUsuario.setCarrera("Petrolera");
                ObAn.catalogo1.labelCarrera.setText(inventarioUsuario.getCarrera());
                colocarFoto(ObAn.catalogo1.labelCamisaMC, 129);
                colocarFoto(ObAn.catalogo1.labelCamisaML, 135);
                colocarFoto(ObAn.catalogo1.labelPlayera, 141);
                ObAn.animacionCatalogo(ObAn.catalogo2, ObAn.catalogo1);
                break;

            case 8:
                botonSiguiente.setVisible(false);
                ObAn.inventarioUsuario.setCarrera("Renovables");
                ObAn.catalogo2.labelCarrera.setText(inventarioUsuario.getCarrera());
                colocarFoto(ObAn.catalogo2.labelCamisaMC, 147);
                colocarFoto(ObAn.catalogo2.labelCamisaML, 153);
                colocarFoto(ObAn.catalogo2.labelPlayera, 159);
                ObAn.animacionCatalogo(ObAn.catalogo1, ObAn.catalogo2);
                break;

        }
    }

    public void visualizarBotonesNavegacion(boolean estado) {
        botonAtras.setVisible(estado);
        botonSiguiente.setVisible(estado);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAtras;
    public javax.swing.JButton botonSiguiente;
    public javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
