/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.usuario;

import Ventanas.admin.*;
import Externos.CambiarPanel;
import Objetos.Carrito;
import Objetos.Inventario;
import Objetos.ObAn;
import Vista.Plantilla;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageOutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class VisualizarProducto extends javax.swing.JPanel {

    /**
     * Creates new form AdminModificar
     */
    byte arrayBytes[];
    public Inventario inventario;
    public Inventario inventarioFoto;
    int cantidad = 0;

    //ArrayList<Carrito> listaCarrito = new ArrayList<>();
    //Object datos[] = new Object[10];
    public VisualizarProducto() {
        initComponents();
        labelMujer.setVisible(false);
        labelMediano.setVisible(false);
        labelGrande.setVisible(false);

        txtFieldCantidad.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelStock = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnHombre = new javax.swing.JButton();
        btnMujer = new javax.swing.JButton();
        labelMediano = new javax.swing.JLabel();
        labelGrande = new javax.swing.JLabel();
        labelChico = new javax.swing.JLabel();
        labelMujer = new javax.swing.JLabel();
        labelHombre = new javax.swing.JLabel();
        btnTallaChica = new javax.swing.JButton();
        btnTallaMediana = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnTallaGrande = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        txtFieldCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStock.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        labelStock.setForeground(new java.awt.Color(255, 255, 255));
        labelStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 391, 60, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-1.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 4, 84, 85));

        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 160, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMas(usuario.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMas2(usuario).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 462, 46, 46));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMenos(usuario).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMenos2(usuario).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 465, 46, 46));

        btnHombre.setBorder(null);
        btnHombre.setContentAreaFilled(false);
        btnHombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHombreActionPerformed(evt);
            }
        });
        add(btnHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 290, 20, 20));

        btnMujer.setBorder(null);
        btnMujer.setContentAreaFilled(false);
        btnMujer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMujerActionPerformed(evt);
            }
        });
        add(btnMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 30, 20));

        labelMediano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonMediano.png"))); // NOI18N
        add(labelMediano, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 350, 40, 40));

        labelGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonGrande.png"))); // NOI18N
        add(labelGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 350, 40, 40));

        labelChico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonChico.png"))); // NOI18N
        labelChico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(labelChico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 40, 40));

        labelMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonMujer.png"))); // NOI18N
        labelMujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMujerMouseClicked(evt);
            }
        });
        add(labelMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 278, 40, 40));

        labelHombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonHombre.png"))); // NOI18N
        add(labelHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 278, 40, 40));

        btnTallaChica.setBorder(null);
        btnTallaChica.setContentAreaFilled(false);
        btnTallaChica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTallaChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTallaChicaActionPerformed(evt);
            }
        });
        add(btnTallaChica, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 20, 20));

        btnTallaMediana.setBorder(null);
        btnTallaMediana.setContentAreaFilled(false);
        btnTallaMediana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTallaMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTallaMedianaActionPerformed(evt);
            }
        });
        add(btnTallaMediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 20, 20));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AGREGAR ORIGINAL.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AGREGAR.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 522, 433, 71));

        btnTallaGrande.setBorder(null);
        btnTallaGrande.setContentAreaFilled(false);
        btnTallaGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTallaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTallaGrandeActionPerformed(evt);
            }
        });
        add(btnTallaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 20, 20));

        labelTitulo.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 440, 70));

        labelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 310, 440));

        labelDescripcion.setFont(new java.awt.Font("Bodoni MT", 0, 22)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDescripcion.setToolTipText("");
        labelDescripcion.setPreferredSize(new java.awt.Dimension(400, 40));
        add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 520, 50));

        txtFieldCantidad.setEditable(false);
        txtFieldCantidad.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldCantidad.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        txtFieldCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtFieldCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldCantidad.setBorder(null);
        add(txtFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VisualizarProducto.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTallaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTallaGrandeActionPerformed
        // TODO add your handling code here:
        labelChico.setVisible(false);
        labelMediano.setVisible(false);
        labelGrande.setVisible(true);
        mostrarDatos();
    }//GEN-LAST:event_btnTallaGrandeActionPerformed

    private void btnTallaChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTallaChicaActionPerformed
        // TODO add your handling code here:
        labelChico.setVisible(true);
        labelMediano.setVisible(false);
        labelGrande.setVisible(false);
        mostrarDatos();
    }//GEN-LAST:event_btnTallaChicaActionPerformed

    private void btnTallaMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTallaMedianaActionPerformed
        // TODO add your handling code here:
        labelGrande.setVisible(false);
        labelChico.setVisible(false);
        labelMediano.setVisible(true);
        mostrarDatos();


    }//GEN-LAST:event_btnTallaMedianaActionPerformed

    private void labelMujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMujerMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_labelMujerMouseClicked

    private void btnHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHombreActionPerformed
        // TODO add your handling code here:
        labelMujer.setVisible(false);
        labelHombre.setVisible(true);
        ObAn.inventarioUsuario.setSexo("Hombre");
        obtenerFotoCorrespondiente();
        inventario = new SQL.Conexion().obtenerStock(ObAn.inventarioUsuario.getEscuela(), ObAn.inventarioUsuario.getCarrera(), ObAn.inventarioUsuario.getTipo(), ObAn.inventarioUsuario.getSexo(), ObAn.inventarioUsuario.getTalla());
        ObAn.mostrarInformacionUsuario(inventario, 2);

    }//GEN-LAST:event_btnHombreActionPerformed

    private void btnMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMujerActionPerformed
        // TODO add your handling code here:
        labelMujer.setVisible(true);
        labelHombre.setVisible(false);
        ObAn.inventarioUsuario.setSexo("Mujer");
        obtenerFotoCorrespondiente();
        inventario = new SQL.Conexion().obtenerStock(ObAn.inventarioUsuario.getEscuela(), ObAn.inventarioUsuario.getCarrera(), ObAn.inventarioUsuario.getTipo(), ObAn.inventarioUsuario.getSexo(), ObAn.inventarioUsuario.getTalla());
        ObAn.mostrarInformacionUsuario(inventario, 2);
    }//GEN-LAST:event_btnMujerActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        int cantidadArticulos = Integer.parseInt(txtFieldCantidad.getText());
        System.out.println(inventario.getStock());

        if (inventario.getStock() == 0) {

            //JOptionPane.showMessageDialog(null, "Producto agotado carnal.");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ProductoAgotado.png"));
            ObAn.popUpErrorPlantilla.setVisible(true);
        } else {

            if (cantidadArticulos > inventario.getStock()) {

                //JOptionPane.showMessageDialog(null, "La cantidad que has ingresado sobrepasa el stock disponible.");
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/AlertaStock.png"));
                ObAn.popUpErrorPlantilla.setVisible(true);

            } else if (cantidadArticulos == 0) {
                //JOptionPane.showMessageDialog(null, "No puedes comprar 0 articulos");
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/NoPuedesComprar0.png"));
                ObAn.popUpErrorPlantilla.setVisible(true);

            } else if (cantidadArticulos <= inventario.getStock()) {
                //Proceso que no deberia de estar aqui
                //Esta en mi bloc de notas xd

                //Convierto la foto del label en un array de byte
                ImageIcon imagenUniforme = (ImageIcon) labelImagen.getIcon();
                imageToArray(imagenUniforme);
                //Hago una lista de objetos de tipo inventario. (simulacion de carrito)
                int precioVenta = inventario.getPrecio() * cantidadArticulos;
                ObAn.user.carrito.add(new Carrito(inventario.getIdProducto(), cantidadArticulos, precioVenta, inventario.getDescripcion(), arrayBytes, inventario.getPrecio()));
                for (int i = 0; i < ObAn.user.carrito.size(); i++) {

                    System.out.println(ObAn.user.carrito.get(i).getDescripcion());
                }

                System.out.println(cantidadArticulos);

                /* El codigo de abajo me marcaba error asi q lo comente, no se que haga, pero csm.
            ObAn.ventas.setUnidades(cantidadArticulos);
            ObAn.ventas.setPrecioVenta(inventario.getPrecio() * cantidadArticulos);
            ObAn.ventas.setFechaVenta("NULL");
            ObAn.ventas.setIdProducto(inventario.getIdProducto());
            ObAn.ventas.setIdUsuario(ObAn.usuario.getIdUsuario());
            
            new SQL.Conexion().agregarAlCarrito(ObAn.ventas.getUnidades(), ObAn.ventas.getPrecioVenta(), ObAn.ventas.getFechaVenta(), ObAn.ventas.getIdProducto(), ObAn.ventas.getIdUsuario());
                 */
                //JOptionPane.showMessageDialog(null, "Producto agregado con exito al carrito");
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ProductoAgregado.png"));
                ObAn.popUpErrorPlantilla.setVisible(true);
                seteoValores();

            }
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cantidad != 0) {
            cantidad--;
            txtFieldCantidad.setText(String.valueOf(cantidad));

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (cantidad <= 20) {
            cantidad++;
            txtFieldCantidad.setText(String.valueOf(cantidad));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        identificarGuiaDeTallas();
        new CambiarPanel(Plantilla.jPanel1, ObAn.guiaTallas);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        //Cada que se regrese, se setearan los valores por defecto.
        seteoValores();

    }//GEN-LAST:event_jButton5ActionPerformed

    public void mostrarDatos() {
        if (labelHombre.isVisible()) {
            if (labelChico.isVisible()) {
                ObAn.inventarioUsuario.setTalla(32);

            } else if (labelMediano.isVisible()) {

                ObAn.inventarioUsuario.setTalla(34);

            } else if (labelGrande.isVisible()) {
                ObAn.inventarioUsuario.setTalla(36);

            }
        } else if (labelMujer.isVisible()) {
            if (labelChico.isVisible()) {
                ObAn.inventarioUsuario.setTalla(32);

            } else if (labelMediano.isVisible()) {

                ObAn.inventarioUsuario.setTalla(34);

            } else if (labelGrande.isVisible()) {
                ObAn.inventarioUsuario.setTalla(36);
            }
        }
        inventario = new SQL.Conexion().obtenerStock(ObAn.inventarioUsuario.getEscuela(), ObAn.inventarioUsuario.getCarrera(), ObAn.inventarioUsuario.getTipo(), ObAn.inventarioUsuario.getSexo(), ObAn.inventarioUsuario.getTalla());
        ObAn.mostrarInformacionUsuario(inventario, 2);

    }

    public void obtenerFotoCorrespondiente() {
        inventarioFoto = new SQL.Conexion().obtenerStock(ObAn.inventarioUsuario.getEscuela(), ObAn.inventarioUsuario.getCarrera(), ObAn.inventarioUsuario.getTipo(), ObAn.inventarioUsuario.getSexo(), 32);
        labelImagen.setIcon(ObAn.conversionFoto(inventarioFoto.getFoto()));

    }

    public void imageToArray(ImageIcon imgIcon) {
        Icon icon = imgIcon;
        BufferedImage img = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = img.createGraphics();
        icon.paintIcon(null, g2d, 0, 0);
        g2d.dispose();

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            ImageOutputStream ios = ImageIO.createImageOutputStream(baos);
            try {
                ImageIO.write(img, "jpg", ios);
                // Set a flag to indicate that the write was successful
            } finally {
                ios.close();
            }
            arrayBytes = baos.toByteArray();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public void seteoValores() {

        //Primero checo si esta en estas ventanas
        if (ObAn.inventarioUsuario.getEscuela().equals("TEPEYAC") || ObAn.inventarioUsuario.getEscuela().equals("COBAEV")) {
            //Despues agrego el catalogo 1 al contenedor de la interfaz user
            new CambiarPanel(ObAn.user.contenedor, ObAn.catalogo1);
            ObAn.user.botonSiguiente.setVisible(true);
            ObAn.user.botonAtras.setVisible(false);
            ObAn.user.contadorClick = 0;
            ObAn.inventarioUsuario.setEscuela("ITSPR");
            ObAn.inventarioUsuario.setCarrera("Ing. en sistemas");
            ObAn.inventarioUsuario.setTipo("");
            ObAn.colocarFoto(ObAn.catalogo1.labelCamisaMC, 3);
            ObAn.colocarFoto(ObAn.catalogo1.labelCamisaML, 9);
            ObAn.colocarFoto(ObAn.catalogo1.labelPlayera, 15);

        }
        ObAn.inventarioUsuario.setTalla(32);
        ObAn.inventarioUsuario.setSexo("Hombre");
        new CambiarPanel(Plantilla.jPanel1, ObAn.user);
        labelHombre.setVisible(true);
        labelChico.setVisible(true);
        labelMujer.setVisible(false);
        labelMediano.setVisible(false);
        labelGrande.setVisible(false);
        txtFieldCantidad.setText("0");
        cantidad = 0;

    }

    public void identificarGuiaDeTallas() {

        if (inventario.getTipo().equals("Camisa manga larga")) {

            if (inventario.getSexo().trim().equals("Hombre")) {

                ObAn.guiaTallas.labelGuiaTallas.setIcon(new ImageIcon("src/Imagenes/GuiaHombreCamisaLarga.png"));
            } else if (inventario.getSexo().trim().equals("Mujer")) {
                ObAn.guiaTallas.labelGuiaTallas.setIcon(new ImageIcon("src/Imagenes/GuiaMujerCamisaLarga.png"));
            }

        } else if (inventario.getTipo().equals("Camisa manga corta")) {
            if (inventario.getSexo().trim().equals("Hombre")) {

                ObAn.guiaTallas.labelGuiaTallas.setIcon(new ImageIcon("src/Imagenes/GuiaHombreCamisaCorta.png"));
            } else if (inventario.getSexo().trim().equals("Mujer")) {
                ObAn.guiaTallas.labelGuiaTallas.setIcon(new ImageIcon("src/Imagenes/GuiaMujerCamisaCorta.png"));
            }

        } else if (inventario.getTipo().equals("Playera")) {
            if (inventario.getSexo().trim().equals("Hombre")) {

                ObAn.guiaTallas.labelGuiaTallas.setIcon(new ImageIcon("src/Imagenes/GuiaHombreCamisa.png"));
            } else if (inventario.getSexo().trim().equals("Mujer")) {
                ObAn.guiaTallas.labelGuiaTallas.setIcon(new ImageIcon("src/Imagenes/GuiaMujerCamisa.png"));
            }
        }
        else if (inventario.getTipo().equals("Chaleco")) {
            if (inventario.getSexo().trim().equals("Hombre")) {

                ObAn.guiaTallas.labelGuiaTallas.setIcon(new ImageIcon("src/Imagenes/GuiaHombreChaleco.png"));
            } else if (inventario.getSexo().trim().equals("Mujer")) {
                ObAn.guiaTallas.labelGuiaTallas.setIcon(new ImageIcon("src/Imagenes/GuiaMujerChaleco.png"));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHombre;
    private javax.swing.JButton btnMujer;
    private javax.swing.JButton btnTallaChica;
    private javax.swing.JButton btnTallaGrande;
    private javax.swing.JButton btnTallaMediana;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelChico;
    public javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelGrande;
    private javax.swing.JLabel labelHombre;
    public javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelMediano;
    private javax.swing.JLabel labelMujer;
    public javax.swing.JLabel labelStock;
    public javax.swing.JLabel labelTitulo;
    public javax.swing.JTextField txtFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
