/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.login;

import Objetos.ObAn;
import Vista.Plantilla;
import Externos.*;
import PopUps.*;
import bijou.Bijou;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pahcual
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    
    String recordarCorreo;
    String recordarContraseña;
    public static boolean loginAdminOrUser;

    public Login() {
        
        initComponents();
        Objetos.ObAn.placeHolder("Usuario", email);
        Objetos.ObAn.placeHolder("Password", password);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrearCuenta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCrearCuenta.setBorder(null);
        jButtonCrearCuenta.setBorderPainted(false);
        jButtonCrearCuenta.setContentAreaFilled(false);
        jButtonCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCuentaActionPerformed(evt);
            }
        });
        add(jButtonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 255, 30));

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 406, 360, 20));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresar-1.png"))); // NOI18N
        btnIngresar.setBorder(null);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setFocusPainted(false);
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresar-2.png"))); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 520, 290, 90));

        email.setBackground(new java.awt.Color(196, 196, 196));
        email.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 242, 440, 38));

        password.setBackground(new java.awt.Color(196, 196, 196));
        password.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 341, 440, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String correo = email.getText();
        String pasword = new String(password.getPassword()).trim();
        if (new SQL.Conexion().verificarExistenciaUsuario(correo)) {
            if (new SQL.Conexion().verificarContraseña(correo, pasword)) {

                if (loginAdminOrUser) {
                    Objetos.ObAn.animacionLoginToHomeAdmin();
                    cambiarIconMinimizar("src/Imagenes/Minimizar-1 (blancoverde).png", "src/Imagenes/Minimizar-2 (blancoverde).png");
                    cambiarIconCerrar("src/Imagenes/Cerrar-1 (blancoverde).png", "src/Imagenes/Cerrar-2 (blancoverde).png");
                } else {
                    ObAn.user.contenedor.add(ObAn.catalogo1);
                    Objetos.ObAn.animacionLoginToHomeUser();
                    Objetos.ObAn.usuario = new SQL.Conexion().obtenerDatosUsuario(correo, pasword);
                    System.out.println(Objetos.ObAn.usuario.getIdUsuario());
                    this.email.setText("");
                    this.password.setText("");
                    cambiarIconMinimizar("src/Imagenes/Minimizar-1 (blancoverde).png", "src/Imagenes/Minimizar-2 (blancoverde).png");
                    cambiarIconCerrar("src/Imagenes/Cerrar-1 (blancoverde).png", "src/Imagenes/Cerrar-2 (blancoverde).png");
                }
            } else {
                //JOptionPane.showMessageDialog(null, "La contraseña no es correcta.");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ContraseñaIncorrecta.png"));
            //ObAn.popUpErrorPlantilla = new PopUpError();
            ObAn.popUpErrorPlantilla.setVisible(true);
            }
        } else {
            //JOptionPane.showMessageDialog(null, "El usuario no existe, favor de registrarse");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ElUsuarioNoExiste.png"));
            ObAn.popUpErrorPlantilla.setVisible(true);
        }


    }//GEN-LAST:event_btnIngresarActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_passwordActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButtonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCuentaActionPerformed
        // TODO add your handling code here:

        new CambiarPanel(Plantilla.jPanel1, ObAn.register);
        //new CambiarPanel(Plantilla.jPanel1, Objetos.ObAn.register);
        /*
        JPanel jp1 = Plantilla.jPanel1;
        jp1.removeAll();
        jp1.revalidate();
        jp1.repaint();

        jp1.add(Objetos.ObAn.register);
        jp1.revalidate();
        jp1.repaint();
         */

    }//GEN-LAST:event_jButtonCrearCuentaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(ObAn.vd2.jPanel1, ObAn.restablecer);
        ObAn.vd2.setVisible(true);
        

        /*
        Prueba prueba = new Prueba();
        this.jDesktopPane1.add(prueba);
        prueba.setVisible(true);
        this.jButton2.setEnabled(false);
         */
    }//GEN-LAST:event_jButton2ActionPerformed
 
public void cambiarIconMinimizar(String rutaIcon, String rutaRolloverIcon){
    bijou.Bijou.pg.btnMinimizar.setIcon(new ImageIcon(rutaIcon));
    bijou.Bijou.pg.btnMinimizar.setRolloverIcon(new ImageIcon(rutaRolloverIcon));
            
           
}

public void cambiarIconCerrar(String rutaIcon, String rutaRolloverIcon){
    bijou.Bijou.pg.btnCerrar.setIcon(new ImageIcon(rutaIcon));
    bijou.Bijou.pg.btnCerrar.setRolloverIcon(new ImageIcon(rutaRolloverIcon));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCrearCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
