/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.admin;

import Externos.CambiarPanel;
import Objetos.ObAn;
import Vista.Plantilla;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class AdminRegistrarComprador extends javax.swing.JPanel {

    /**
     * Creates new form AdminRegistrarComprador
     */
    String nombreC;
    String telefono;
    String correo;
    String estado;
    String ciudad;
    String direccion;

    public AdminRegistrarComprador() {
        initComponents();
        Objetos.ObAn.placeHolder("Ej. Jorge Alejandro Ramirez Pascual", txtFieldNombre);
        Objetos.ObAn.placeHolder("784213", txtFieldTelefono);
        Objetos.ObAn.placeHolder("jorgePahcual@hotmail.com", txtFieldCorreo);
        Objetos.ObAn.placeHolder("Veracruz", txtFieldEstado);
        Objetos.ObAn.placeHolder("Poza Rica", txtFieldCiudad);
        Objetos.ObAn.placeHolder("Calle Vicente G. Col. Laredo #152", txtFieldDireccion);
    }

    public void seteoGlobal() {
        txtFieldNombre.setText("");
        txtFieldTelefono.setText("");
        txtFieldCorreo.setText("");
        txtFieldEstado.setText("");
        txtFieldCiudad.setText("");
        txtFieldDireccion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtFieldTelefono = new javax.swing.JTextField();
        txtFieldNombre = new javax.swing.JTextField();
        txtFieldCorreo = new javax.swing.JTextField();
        txtFieldEstado = new javax.swing.JTextField();
        txtFieldDireccion = new javax.swing.JTextField();
        txtFieldCiudad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 4, 84, 85));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-1 (registronuevousuario).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-2 (registronuevousuario).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 638, 264, 86));

        txtFieldTelefono.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldTelefono.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtFieldTelefono.setBorder(null);
        add(txtFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 320, 290, 30));

        txtFieldNombre.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldNombre.setBorder(null);
        add(txtFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 200, 620, 40));

        txtFieldCorreo.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldCorreo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtFieldCorreo.setBorder(null);
        txtFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCorreoActionPerformed(evt);
            }
        });
        add(txtFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 320, 290, 30));

        txtFieldEstado.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldEstado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtFieldEstado.setBorder(null);
        add(txtFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 440, 290, 40));

        txtFieldDireccion.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldDireccion.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtFieldDireccion.setBorder(null);
        add(txtFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 560, 850, 40));

        txtFieldCiudad.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldCiudad.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtFieldCiudad.setBorder(null);
        add(txtFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 440, 290, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin 4.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nombreC = txtFieldNombre.getText();
        telefono = txtFieldTelefono.getText();
        correo = txtFieldCorreo.getText();
        estado = txtFieldEstado.getText();
        ciudad = txtFieldCiudad.getText();
        direccion = txtFieldDireccion.getText();
        new SQL.Conexion().insertarCompradorMayoreo(nombreC, telefono, correo, estado, ciudad, direccion);
        ObAn.adminRegistrarComprador2.labelNombre.setText(nombreC);
        ObAn.adminRegistrarComprador2.labelTelefono.setText(telefono);
        ObAn.adminRegistrarComprador2.labelCorreo.setText(correo);
        ObAn.adminRegistrarComprador2.labelEstado.setText(estado);
        ObAn.adminRegistrarComprador2.labelCiudad.setText(ciudad);

        //JOptionPane.showMessageDialog(null, "Comprador registrado con exito.");
        ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/CompradorRegistrado.png"));
        ObAn.popUpErrorPlantilla.setVisible(true);
        seteoGlobal();
        new CambiarPanel(Plantilla.jPanel1, ObAn.adminRegistrarComprador2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(Plantilla.jPanel1, ObAn.admin1);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFieldCiudad;
    private javax.swing.JTextField txtFieldCorreo;
    private javax.swing.JTextField txtFieldDireccion;
    private javax.swing.JTextField txtFieldEstado;
    private javax.swing.JTextField txtFieldNombre;
    private javax.swing.JTextField txtFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
