/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.admin;

import Externos.CambiarPanel;
import Objetos.ObAn;
import Vista.Plantilla;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author PC
 */
public class AdminRegistrarComprador2 extends javax.swing.JPanel {

    /**
     * Creates new form AdminRegistrarComprador
     */
    String nombreC; 
    String telefono;
    String correo; 
    String estado; 
    String ciudad;
    String productos;
    String total;
    
    public AdminRegistrarComprador2() {
        initComponents();
        Objetos.ObAn.placeHolder("$256", txtFieldPrecioTotal);
        
         
    }
    public void seteoGlobal(){
        labelNombre.setText("");
        labelTelefono.setText("");
        labelCorreo.setText("");
        labelEstado.setText("");
        labelCiudad.setText("");
        txtFieldPrecioTotal.setText("");
        jTextArea1.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCiudad = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        txtFieldPrecioTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCiudad.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 306, 290, 30));

        labelNombre.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 146, 390, 30));

        labelEstado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        add(labelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 268, 290, 30));

        labelCorreo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 290, 30));

        labelTelefono.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 189, 290, 30));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 640, 240, 70));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(196, 196, 196));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 470, 330));

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 60));

        txtFieldPrecioTotal.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldPrecioTotal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtFieldPrecioTotal.setBorder(null);
        add(txtFieldPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 454, 230, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin 6.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(Plantilla.jPanel1, ObAn.admin1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        try{
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte.pdf"));

            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.setFont(FontFactory.getFont("Tahoma", 20, Font.BOLD, BaseColor.DARK_GRAY));
            parrafo.add("\nU N I F O R M E S  B I J O U  \n\n");

            parrafo.setAlignment(Paragraph.ALIGN_LEFT);
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Nombre: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(labelNombre.getText() + "\n\n");

            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Telefono: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(labelTelefono.getText() + "\n\n");

            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Correo: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(labelCorreo.getText() + "\n\n");

            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Estado: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(labelEstado.getText() + "\n\n");

            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Ciudad: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(labelCiudad.getText() + "\n\n");

            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Productos: \n\n");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(jTextArea1.getText() + "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");

            Image imagen = Image.getInstance("src/imagenes/Cabecera.png");
            imagen.scaleToFit(2480, 100);
            imagen.setAlignment(Chunk.ALIGN_CENTER);

            Image imagen2 = Image.getInstance("src/imagenes/Pie.png");
            imagen2.scaleToFit(2480, 100);
            imagen2.setAlignment(Chunk.ALIGN_CENTER);

            documento.open();
            documento.add(imagen);
            documento.add(parrafo);
            documento.add(imagen2);
            documento.close();

        }catch(Exception e){

        }
        //JOptionPane.showMessageDialog(null, "PDF generado con exito.");
        ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/PDFgenerado.png"));
            ObAn.popUpErrorPlantilla.setVisible(true);
        
        seteoGlobal();
        new CambiarPanel(Plantilla.jPanel1, ObAn.admin1);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel labelCiudad;
    public javax.swing.JLabel labelCorreo;
    public javax.swing.JLabel labelEstado;
    public javax.swing.JLabel labelNombre;
    public javax.swing.JLabel labelTelefono;
    private javax.swing.JTextField txtFieldPrecioTotal;
    // End of variables declaration//GEN-END:variables
}
