/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.admin;

import Externos.CambiarPanel;
import Objetos.Inventario;
import Objetos.ObAn;
import Vista.Plantilla;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PanelEditarProducto extends javax.swing.JPanel {

    /**
     * Creates new form AdminModificar
     */
    public Inventario inventarioFoto;
    public Inventario inventario;

    public PanelEditarProducto() {
        initComponents();
        labelMujer.setVisible(false);
        labelMediano.setVisible(false);
        labelGrande.setVisible(false);
        btnGuardar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        btnHombre = new javax.swing.JButton();
        btnMujer = new javax.swing.JButton();
        labelMediano = new javax.swing.JLabel();
        labelGrande = new javax.swing.JLabel();
        labelChico = new javax.swing.JLabel();
        labelMujer = new javax.swing.JLabel();
        labelHombre = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnTallaChica = new javax.swing.JButton();
        btnTallaMediana = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnTallaGrande = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        txtFieldCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 4, 84, 85));

        btnHombre.setBorder(null);
        btnHombre.setContentAreaFilled(false);
        btnHombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHombre.setFocusPainted(false);
        btnHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHombreActionPerformed(evt);
            }
        });
        add(btnHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 290, 20, 20));

        btnMujer.setBorder(null);
        btnMujer.setContentAreaFilled(false);
        btnMujer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMujer.setFocusPainted(false);
        btnMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMujerActionPerformed(evt);
            }
        });
        add(btnMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 30, 20));

        labelMediano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonMediano.png"))); // NOI18N
        add(labelMediano, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 350, 40, 40));

        labelGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonGrande.png"))); // NOI18N
        add(labelGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 350, 40, 40));

        labelChico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonChico.png"))); // NOI18N
        add(labelChico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 40, 40));

        labelMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonMujer.png"))); // NOI18N
        labelMujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMujerMouseClicked(evt);
            }
        });
        add(labelMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 278, 40, 40));

        labelHombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonHombre.png"))); // NOI18N
        add(labelHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 278, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar(admin).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar2(admin).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 535, 181, 56));

        btnTallaChica.setBorder(null);
        btnTallaChica.setContentAreaFilled(false);
        btnTallaChica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTallaChica.setFocusPainted(false);
        btnTallaChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTallaChicaActionPerformed(evt);
            }
        });
        add(btnTallaChica, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 20, 20));

        btnTallaMediana.setBorder(null);
        btnTallaMediana.setContentAreaFilled(false);
        btnTallaMediana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTallaMediana.setFocusPainted(false);
        btnTallaMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTallaMedianaActionPerformed(evt);
            }
        });
        add(btnTallaMediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 20, 20));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar(admin).png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setEnabled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar2(admin).png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 535, 181, 56));

        btnTallaGrande.setBorder(null);
        btnTallaGrande.setContentAreaFilled(false);
        btnTallaGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTallaGrande.setFocusPainted(false);
        btnTallaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTallaGrandeActionPerformed(evt);
            }
        });
        add(btnTallaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 20, 20));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 420, 50));

        labelTitulo.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 440, 70));

        labelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 310, 440));

        labelDescripcion.setFont(new java.awt.Font("Bodoni MT", 0, 22)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDescripcion.setToolTipText("");
        labelDescripcion.setPreferredSize(new java.awt.Dimension(400, 40));
        add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 520, 50));

        txtFieldCantidad.setEditable(false);
        txtFieldCantidad.setBackground(new java.awt.Color(196, 196, 196));
        txtFieldCantidad.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        txtFieldCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtFieldCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldCantidad.setBorder(null);
        txtFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCantidadActionPerformed(evt);
            }
        });
        add(txtFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 473, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PanelEditarProducto.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //new CambiarPanel(Plantilla.jPanel1, ObAn.admin3);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTallaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTallaGrandeActionPerformed
        // TODO add your handling code here:
        labelChico.setVisible(false);
        labelMediano.setVisible(false);
        labelGrande.setVisible(true);
        mostrarDatos();
    }//GEN-LAST:event_btnTallaGrandeActionPerformed

    private void btnTallaChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTallaChicaActionPerformed
        // TODO add your handling code here:
        labelChico.setVisible(true);
        labelMediano.setVisible(false);
        labelGrande.setVisible(false);
        mostrarDatos();
    }//GEN-LAST:event_btnTallaChicaActionPerformed

    private void btnTallaMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTallaMedianaActionPerformed
        // TODO add your handling code here:
        labelGrande.setVisible(false);
        labelChico.setVisible(false);
        labelMediano.setVisible(true);
        mostrarDatos();


    }//GEN-LAST:event_btnTallaMedianaActionPerformed

    private void labelMujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMujerMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_labelMujerMouseClicked

    private void btnHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHombreActionPerformed
        // TODO add your handling code here:
        labelMujer.setVisible(false);
        labelHombre.setVisible(true);
        ObAn.inventario.setSexo("Hombre");
        obtenerFotoCorrespondiente();
        inventario = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla());
        ObAn.mostrarInformacion(inventario, 2);
    }//GEN-LAST:event_btnHombreActionPerformed

    private void btnMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMujerActionPerformed
        // TODO add your handling code here:
        labelMujer.setVisible(true);
        labelHombre.setVisible(false);
        ObAn.inventario.setSexo("Mujer");
        obtenerFotoCorrespondiente();
        inventario = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla());
        ObAn.mostrarInformacion(inventario, 2);
    }//GEN-LAST:event_btnMujerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtFieldCantidad.setEditable(true);
        btnGuardar.setEnabled(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        int stock = Integer.parseInt(txtFieldCantidad.getText());

        if (inventario.getStock() != stock) {
            new SQL.Conexion().actualizarStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla(), stock);
            txtFieldCantidad.setEditable(false);
            btnGuardar.setEnabled(false);

        } else {
            //JOptionPane.showMessageDialog(null, "¡Ingresa una cantidad diferente!");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/IngresaUnaCantidadDiferente.png"));
            ObAn.popUpErrorPlantilla.setVisible(true);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ObAn.inventario.setTalla(32);
        ObAn.inventario.setSexo("Hombre");
        txtFieldCantidad.setText("");
        txtFieldCantidad.setEditable(false);
        btnGuardar.setEnabled(false);
        labelHombre.setVisible(true);
        labelChico.setVisible(true);
        labelMujer.setVisible(false);
        labelMediano.setVisible(false);
        labelGrande.setVisible(false);
        if (ObAn.inventario.getEscuela().equals("ITSPR")) {
            new CambiarPanel(Plantilla.jPanel1, ObAn.adminElegirTipoCamisa);
        } else if (ObAn.inventario.getEscuela().equals("UV")) {
            new CambiarPanel(Plantilla.jPanel1, ObAn.adminEelgirCarreraUV);
        } else if (ObAn.inventario.getEscuela().equals("TEPEYAC") || ObAn.inventario.getEscuela().equals("COBAEV")) {
            new CambiarPanel(Plantilla.jPanel1, ObAn.admin2);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCantidadActionPerformed

    public void mostrarDatos() {
        if (labelHombre.isVisible()) {
            if (labelChico.isVisible()) {
                ObAn.inventario.setTalla(32);
                inventario = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla());
                ObAn.mostrarInformacion(inventario, 2);
            } else if (labelMediano.isVisible()) {

                ObAn.inventario.setTalla(34);
                inventario = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla());
                ObAn.mostrarInformacion(inventario, 2);
            } else if (labelGrande.isVisible()) {
                ObAn.inventario.setTalla(36);
                inventario = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla());
                ObAn.mostrarInformacion(inventario, 2);
            }
        } else if (labelMujer.isVisible()) {
            if (labelChico.isVisible()) {
                ObAn.inventario.setTalla(32);
                inventario = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla());
                ObAn.mostrarInformacion(inventario, 2);
            } else if (labelMediano.isVisible()) {

                ObAn.inventario.setTalla(34);
                inventario = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla());
                ObAn.mostrarInformacion(inventario, 2);
            } else if (labelGrande.isVisible()) {
                ObAn.inventario.setTalla(36);
                inventario = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), ObAn.inventario.getTalla());
                ObAn.mostrarInformacion(inventario, 2);
            }
        }
    }

    public void obtenerFotoCorrespondiente() {
        inventarioFoto = new SQL.Conexion().obtenerStock(ObAn.inventario.getEscuela(), ObAn.inventario.getCarrera(), ObAn.inventario.getTipo(), ObAn.inventario.getSexo(), 32);
        labelImagen.setIcon(ObAn.conversionFoto(inventarioFoto.getFoto()));

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHombre;
    private javax.swing.JButton btnMujer;
    private javax.swing.JButton btnTallaChica;
    private javax.swing.JButton btnTallaGrande;
    private javax.swing.JButton btnTallaMediana;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelChico;
    public javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelGrande;
    private javax.swing.JLabel labelHombre;
    public javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelMediano;
    private javax.swing.JLabel labelMujer;
    public javax.swing.JLabel labelTitulo;
    public javax.swing.JTextField txtFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
