/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Externos.CambiarPanel;
import Objetos.ObAn;
import SQL.Conexion;
import Vista.Plantilla;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class RegistroTarjeta extends javax.swing.JPanel {

    /**
     * Creates new form Registrotarjeta
     */
    String sNombre, sNumeroTarjeta, sFechaExp, sCVC;

    public RegistroTarjeta() {
        initComponents();
        ObAn.placeHolder("Jorge Alejandro", nombreTitular);
        ObAn.placeHolder("****************", numeroTarjeta);
        ObAn.placeHolder("06", expM);
        ObAn.placeHolder("23", expA);
        ObAn.placeHolder("1234", cvc);
        tarjetaValida.setVisible(false);
        tarjetaInvalida.setVisible(false);
        seteoLabel(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorFecha = new javax.swing.JLabel();
        tarjetaInvalida = new javax.swing.JLabel();
        tarjetaValida = new javax.swing.JLabel();
        errorNombre = new javax.swing.JLabel();
        errorTarjeta = new javax.swing.JLabel();
        errorCVC = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        expM = new javax.swing.JTextField();
        expA = new javax.swing.JTextField();
        nombreTitular = new javax.swing.JTextField();
        cvc = new javax.swing.JTextField();
        numeroTarjeta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorFecha.setForeground(new java.awt.Color(255, 64, 64));
        errorFecha.setText("Datos obligatorio");
        add(errorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 344, -1, -1));

        tarjetaInvalida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tarjetaInvalida.setForeground(new java.awt.Color(255, 64, 64));
        tarjetaInvalida.setText("Tarjeta no valida");
        add(tarjetaInvalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 214, -1, -1));

        tarjetaValida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tarjetaValida.setForeground(new java.awt.Color(51, 204, 0));
        tarjetaValida.setText("Tarjeta valida");
        add(tarjetaValida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 214, -1, -1));

        errorNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorNombre.setForeground(new java.awt.Color(255, 64, 64));
        errorNombre.setText("Dato obligatorio");
        add(errorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        errorTarjeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorTarjeta.setForeground(new java.awt.Color(255, 64, 64));
        errorTarjeta.setText("Dato obligatorio");
        add(errorTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 214, -1, -1));

        errorCVC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorCVC.setForeground(new java.awt.Color(255, 64, 64));
        errorCVC.setText("Dato obligatorio");
        add(errorCVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 344, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-1 (tarjeta).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-2 (tarjeta).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 184, 80));

        expM.setBackground(new java.awt.Color(196, 196, 196));
        expM.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        expM.setForeground(new java.awt.Color(255, 255, 255));
        expM.setBorder(null);
        expM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                expMFocusLost(evt);
            }
        });
        expM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expMActionPerformed(evt);
            }
        });
        expM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expMKeyTyped(evt);
            }
        });
        add(expM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 378, 90, 30));

        expA.setBackground(new java.awt.Color(196, 196, 196));
        expA.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        expA.setForeground(new java.awt.Color(255, 255, 255));
        expA.setBorder(null);
        expA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                expAFocusLost(evt);
            }
        });
        expA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expAActionPerformed(evt);
            }
        });
        expA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expAKeyTyped(evt);
            }
        });
        add(expA, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 378, 90, 30));

        nombreTitular.setBackground(new java.awt.Color(196, 196, 196));
        nombreTitular.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nombreTitular.setForeground(new java.awt.Color(255, 255, 255));
        nombreTitular.setBorder(null);
        nombreTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTitularFocusLost(evt);
            }
        });
        nombreTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTitularActionPerformed(evt);
            }
        });
        nombreTitular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTitularKeyTyped(evt);
            }
        });
        add(nombreTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 440, 38));

        cvc.setBackground(new java.awt.Color(196, 196, 196));
        cvc.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cvc.setForeground(new java.awt.Color(255, 255, 255));
        cvc.setBorder(null);
        cvc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cvcFocusLost(evt);
            }
        });
        cvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvcActionPerformed(evt);
            }
        });
        cvc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvcKeyTyped(evt);
            }
        });
        add(cvc, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 130, 30));

        numeroTarjeta.setBackground(new java.awt.Color(196, 196, 196));
        numeroTarjeta.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        numeroTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        numeroTarjeta.setBorder(null);
        numeroTarjeta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroTarjetaFocusLost(evt);
            }
        });
        numeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjetaActionPerformed(evt);
            }
        });
        numeroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroTarjetaKeyTyped(evt);
            }
        });
        add(numeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 440, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroTarjeta.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void numeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTarjetaActionPerformed

    private void cvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvcActionPerformed

    private void nombreTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTitularActionPerformed

    private void expAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expAActionPerformed

    private void expMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getData();
        if (!thereEmptyFields()) {
            seteoLabel(false);
            if (new SQL.Conexion().verificarExistenciaTarjeta(sNumeroTarjeta)) {
                //JOptionPane.showMessageDialog(null, "El numero de tarjeta ya se encuentra registrado");
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/TarjetaRepetida.png"));
                ObAn.popUpErrorPlantilla.setVisible(true);
            } else {
                new Conexion().insertarTarjeta(sNumeroTarjeta, "Debito", sNombre, sFechaExp, Integer.parseInt(sCVC), ObAn.usuario.getIdUsuario());

                //JOptionPane.showMessageDialog(null, "Registro de tarjeta exitosa");
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/RegistroDeTarjetaExitosa.png"));
                ObAn.popUpErrorPlantilla.setVisible(true);
                this.seteoJtextField();
                tarjetaValida.setVisible(false);
                tarjetaInvalida.setVisible(false);
                ObAn.seleccionarMetodoPago.botonVerMetodoPago.setVisible(true);
                new CambiarPanel(ObAn.vd2.jPanel1, ObAn.seleccionarMetodoPago);
            }

        } else {
            //JOptionPane.showMessageDialog(null, "Digita los datos obligatorios.");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/DigitaLosDatos.png"));
            ObAn.popUpErrorPlantilla.setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreTitularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTitularFocusLost
        // TODO add your handling code here:
        activateLabelFocusLost(nombreTitular.getText().trim(), errorNombre);

    }//GEN-LAST:event_nombreTitularFocusLost

    private void numeroTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroTarjetaKeyTyped
        // TODO add your handling code here:
        validateNumbers(evt);
    }//GEN-LAST:event_numeroTarjetaKeyTyped

    private void numeroTarjetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroTarjetaFocusLost
        // TODO add your handling code here:
        activateLabelFocusLost(numeroTarjeta.getText().trim(), errorTarjeta);
    }//GEN-LAST:event_numeroTarjetaFocusLost

    private void nombreTitularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTitularKeyTyped
        // TODO add your handling code here:
        validateCharacters(evt);
    }//GEN-LAST:event_nombreTitularKeyTyped

    private void expMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expMFocusLost
        // TODO add your handling code here:
        activateLabelFocusLost(expM.getText().trim(), errorFecha);
    }//GEN-LAST:event_expMFocusLost

    private void expAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expAFocusLost
        // TODO add your handling code here:
        activateLabelFocusLost(expA.getText().trim(), errorFecha);
    }//GEN-LAST:event_expAFocusLost

    private void expMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expMKeyTyped
        // TODO add your handling code here:
        validateNumbers(evt);
    }//GEN-LAST:event_expMKeyTyped

    private void expAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expAKeyTyped
        // TODO add your handling code here:
        validateNumbers(evt);
    }//GEN-LAST:event_expAKeyTyped

    private void cvcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cvcFocusLost
        // TODO add your handling code here:
        activateLabelFocusLost(cvc.getText().trim(), errorCVC);
    }//GEN-LAST:event_cvcFocusLost

    private void cvcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvcKeyTyped
        // TODO add your handling code here:
        validateNumbers(evt);
    }//GEN-LAST:event_cvcKeyTyped

    private void numeroTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroTarjetaKeyReleased
        // TODO add your handling code here:
        if (numeroTarjeta.getText().length() > 16) {
            tarjetaInvalida.setVisible(true);
            tarjetaValida.setVisible(false);
        } else {
            tarjetaValida.setVisible(true);
            tarjetaInvalida.setVisible(false);
        }
    }//GEN-LAST:event_numeroTarjetaKeyReleased

    public void getData() {
        sNombre = nombreTitular.getText().trim();
        sNumeroTarjeta = numeroTarjeta.getText().trim();
        sFechaExp = expM.getText().trim() + "-" + expA.getText().trim();
        sCVC = cvc.getText().trim();

    }

    public void seteoLabel(boolean b) {

        errorNombre.setVisible(b);
        errorTarjeta.setVisible(b);
        errorFecha.setVisible(b);
        errorCVC.setVisible(b);

    }

    public void activateLabels(boolean b, int n) {
        switch (n) {
            case 0:
                errorNombre.setVisible(b);
                break;
            case 1:
                errorTarjeta.setVisible(b);
                break;
            case 2:
                errorFecha.setVisible(b);
                break;
            case 3:
                errorCVC.setVisible(b);
                break;

        }
    }

    public boolean thereEmptyFields() {

        String data[] = new String[4];
        boolean thereAre = false;
        data[0] = sNombre;
        data[1] = sNumeroTarjeta;
        data[2] = sFechaExp;
        data[3] = sCVC;

        for (int i = 0; i < 4; i++) {
            if (data[i].isEmpty()) {
                thereAre = true;
                activateLabels(true, i);
            }
        }
        return thereAre;
    }

    public void validateCharacters(KeyEvent evt) {

        char c = evt.getKeyChar();

        if (!(Character.isLetter(c) || c == 32 || c == 8)) {
            evt.consume();

        } else {
            System.out.println(c);
        }
    }

    public void validateNumbers(KeyEvent evt) {
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            evt.consume();
        } else {
            System.out.println(c);
        }
    }

    public void activateLabelFocusLost(String s, JLabel label) {
        if (s.isEmpty()) {
            label.setVisible(true);
        } else {
            label.setVisible(false);
        }
    }

    public void seteoJtextField() {
        nombreTitular.setText("");
        numeroTarjeta.setText("");
        expM.setText("");
        expA.setText("");
        cvc.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cvc;
    private javax.swing.JLabel errorCVC;
    private javax.swing.JLabel errorFecha;
    private javax.swing.JLabel errorNombre;
    private javax.swing.JLabel errorTarjeta;
    private javax.swing.JTextField expA;
    private javax.swing.JTextField expM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreTitular;
    private javax.swing.JTextField numeroTarjeta;
    private javax.swing.JLabel tarjetaInvalida;
    private javax.swing.JLabel tarjetaValida;
    // End of variables declaration//GEN-END:variables
}
