/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Externos.CambiarPanel;
import Externos.TextPrompt;
import Objetos.ObAn;
import SQL.Conexion;
import Vista.Plantilla;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Pahcual
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    String sName, sLastName, sEmail, sPassword, sConfirmPassword, sCell;

    public Register() {
        //Olv, son un chingo, me sirve para darle el efecto PlaceHolder a los txtField
        initComponents();
        seteoLabel(false);
        EmailValido.setVisible(false);
        EmailInvalido.setVisible(false);
        ContraseñasIncorrectas.setVisible(false);
        Objetos.ObAn.placeHolder("Nombre", JtfRegisterName);
        Objetos.ObAn.placeHolder("Apellidos", JtfRegisterLastName);
        Objetos.ObAn.placeHolder("Correo electronico", JtfRegisterEmail);
        Objetos.ObAn.placeHolder("Contraseña", JtfRegisterPassword);
        Objetos.ObAn.placeHolder("Confirmar contraseña", JtfRegisterConfirmPassword);
        Objetos.ObAn.placeHolder("Numero telefonico", JtfRegisterCell);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JtfRegisterName = new javax.swing.JTextField();
        JtfRegisterLastName = new javax.swing.JTextField();
        JtfRegisterEmail = new javax.swing.JTextField();
        JtfRegisterPassword = new javax.swing.JPasswordField();
        JtfRegisterCell = new javax.swing.JTextField();
        BtnRegisterBack = new javax.swing.JButton();
        BtnRegisterSucces = new javax.swing.JButton();
        JtfRegisterConfirmPassword = new javax.swing.JPasswordField();
        ContraseñasIncorrectas = new javax.swing.JLabel();
        EmailInvalido = new javax.swing.JLabel();
        EmailValido = new javax.swing.JLabel();
        ErrorCell = new javax.swing.JLabel();
        ErrorEmail = new javax.swing.JLabel();
        ErrorConfirmPassword = new javax.swing.JLabel();
        ErrorPassword = new javax.swing.JLabel();
        ErrorLastName = new javax.swing.JLabel();
        ErrorName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JtfRegisterName.setBackground(new java.awt.Color(196, 196, 196));
        JtfRegisterName.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        JtfRegisterName.setForeground(new java.awt.Color(102, 102, 102));
        JtfRegisterName.setToolTipText("");
        JtfRegisterName.setBorder(null);
        JtfRegisterName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JtfRegisterNameFocusLost(evt);
            }
        });
        JtfRegisterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtfRegisterNameKeyTyped(evt);
            }
        });
        add(JtfRegisterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 161, 290, 30));

        JtfRegisterLastName.setBackground(new java.awt.Color(196, 196, 196));
        JtfRegisterLastName.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        JtfRegisterLastName.setForeground(new java.awt.Color(102, 102, 102));
        JtfRegisterLastName.setBorder(null);
        JtfRegisterLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JtfRegisterLastNameFocusLost(evt);
            }
        });
        JtfRegisterLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtfRegisterLastNameKeyTyped(evt);
            }
        });
        add(JtfRegisterLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 161, 290, 30));

        JtfRegisterEmail.setBackground(new java.awt.Color(196, 196, 196));
        JtfRegisterEmail.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        JtfRegisterEmail.setForeground(new java.awt.Color(102, 102, 102));
        JtfRegisterEmail.setBorder(null);
        JtfRegisterEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JtfRegisterEmailFocusLost(evt);
            }
        });
        JtfRegisterEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtfRegisterEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtfRegisterEmailKeyTyped(evt);
            }
        });
        add(JtfRegisterEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 252, 620, 30));

        JtfRegisterPassword.setBackground(new java.awt.Color(196, 196, 196));
        JtfRegisterPassword.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        JtfRegisterPassword.setForeground(new java.awt.Color(102, 102, 102));
        JtfRegisterPassword.setBorder(null);
        JtfRegisterPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JtfRegisterPasswordFocusLost(evt);
            }
        });
        add(JtfRegisterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 366, 290, 30));

        JtfRegisterCell.setBackground(new java.awt.Color(196, 196, 196));
        JtfRegisterCell.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        JtfRegisterCell.setForeground(new java.awt.Color(102, 102, 102));
        JtfRegisterCell.setBorder(null);
        JtfRegisterCell.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JtfRegisterCellFocusLost(evt);
            }
        });
        JtfRegisterCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfRegisterCellActionPerformed(evt);
            }
        });
        JtfRegisterCell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtfRegisterCellKeyTyped(evt);
            }
        });
        add(JtfRegisterCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 491, 290, 30));

        BtnRegisterBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-1_1.png"))); // NOI18N
        BtnRegisterBack.setBorder(null);
        BtnRegisterBack.setContentAreaFilled(false);
        BtnRegisterBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegisterBack.setFocusPainted(false);
        BtnRegisterBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar-2_1.png"))); // NOI18N
        BtnRegisterBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterBackActionPerformed(evt);
            }
        });
        add(BtnRegisterBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 214, 70));

        BtnRegisterSucces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrarse-1.png"))); // NOI18N
        BtnRegisterSucces.setBorder(null);
        BtnRegisterSucces.setContentAreaFilled(false);
        BtnRegisterSucces.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegisterSucces.setFocusPainted(false);
        BtnRegisterSucces.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrarse-2.png"))); // NOI18N
        BtnRegisterSucces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterSuccesActionPerformed(evt);
            }
        });
        add(BtnRegisterSucces, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 214, 70));

        JtfRegisterConfirmPassword.setBackground(new java.awt.Color(196, 196, 196));
        JtfRegisterConfirmPassword.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        JtfRegisterConfirmPassword.setForeground(new java.awt.Color(102, 102, 102));
        JtfRegisterConfirmPassword.setBorder(null);
        JtfRegisterConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JtfRegisterConfirmPasswordFocusLost(evt);
            }
        });
        JtfRegisterConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtfRegisterConfirmPasswordKeyTyped(evt);
            }
        });
        add(JtfRegisterConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 366, 290, 30));

        ContraseñasIncorrectas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ContraseñasIncorrectas.setForeground(new java.awt.Color(255, 64, 64));
        ContraseñasIncorrectas.setText("Las contraseñas no coinciden");
        add(ContraseñasIncorrectas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 335, -1, -1));

        EmailInvalido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EmailInvalido.setForeground(new java.awt.Color(255, 64, 64));
        EmailInvalido.setText("Email Invalido");
        add(EmailInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 224, -1, -1));

        EmailValido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EmailValido.setForeground(new java.awt.Color(51, 204, 0));
        EmailValido.setText("Email Valido");
        add(EmailValido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 224, -1, -1));

        ErrorCell.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ErrorCell.setForeground(new java.awt.Color(255, 64, 64));
        ErrorCell.setText("Dato obligatorio");
        add(ErrorCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        ErrorEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ErrorEmail.setForeground(new java.awt.Color(255, 64, 64));
        ErrorEmail.setText("Dato obligatorio");
        add(ErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 224, -1, -1));

        ErrorConfirmPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ErrorConfirmPassword.setForeground(new java.awt.Color(255, 64, 64));
        ErrorConfirmPassword.setText("Dato obligatorio");
        add(ErrorConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 335, -1, -1));

        ErrorPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ErrorPassword.setForeground(new java.awt.Color(255, 64, 64));
        ErrorPassword.setText("Dato obligatorio");
        add(ErrorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 335, -1, -1));

        ErrorLastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ErrorLastName.setForeground(new java.awt.Color(255, 64, 64));
        ErrorLastName.setText("Dato obligatorio");
        add(ErrorLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        ErrorName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ErrorName.setForeground(new java.awt.Color(255, 64, 64));
        ErrorName.setText("Dato obligatorio");
        add(ErrorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Register.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegisterBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterBackActionPerformed

        getData();
        if ((sName.equals("") && sLastName.equals("") && sEmail.equals("") && sPassword.equals("")
                && sConfirmPassword.equals("") && sCell.equals(""))) {
            seteoLabel(false);
            EmailValido.setVisible(false);
            EmailInvalido.setVisible(false);
            new CambiarPanel(Vista.Plantilla.jPanel1, ObAn.login);

        } else {

            seteoLabel(false);
            seteoJtextField();
            EmailValido.setVisible(false);
            EmailInvalido.setVisible(false);
            new CambiarPanel(Vista.Plantilla.jPanel1, ObAn.login);

        }

    }//GEN-LAST:event_BtnRegisterBackActionPerformed

    private void BtnRegisterSuccesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterSuccesActionPerformed
        // TODO add your handling code here:
        getData();
        if (!thereEmptyFields()) {
            seteoLabel(false);

            if (sPassword.equals(sConfirmPassword)) {
                if (new Conexion().verificarExistenciaUsuario(sEmail)) {
                    //JOptionPane.showMessageDialog(null, "El email ya se encuentra registrado en la bd, ingresa otro");
                    ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/EmailYaRegistrado.png"));
                    ObAn.popUpErrorPlantilla.setVisible(true);
                } else {
                    new Conexion().insertarCliente(sName, sLastName, sPassword, sEmail, sCell);
                    //JOptionPane.showMessageDialog(null, "Registro exitoso");
                    ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/RegistroExitoso.png"));
                    ObAn.popUpErrorPlantilla.setVisible(true);
                    
                    this.seteoJtextField();
                    EmailValido.setVisible(false);
                    EmailInvalido.setVisible(false);
                    new CambiarPanel(Plantilla.jPanel1, ObAn.login);
                }
            } else {

            }

        } else {
            //JOptionPane.showMessageDialog(null, "Digita los datos obligatorios.");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/DigitaLosDatos.png"));
            ObAn.popUpErrorPlantilla.setVisible(true);
            System.out.println(sName);

        }

    }//GEN-LAST:event_BtnRegisterSuccesActionPerformed

    private void JtfRegisterNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JtfRegisterNameFocusLost
        // TODO add your handling code here:

        activateLabelFocusLost(JtfRegisterName.getText().trim(), ErrorName);

    }//GEN-LAST:event_JtfRegisterNameFocusLost

    private void JtfRegisterLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JtfRegisterLastNameFocusLost
        activateLabelFocusLost(JtfRegisterLastName.getText().trim(), ErrorLastName);
    }//GEN-LAST:event_JtfRegisterLastNameFocusLost

    private void JtfRegisterEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JtfRegisterEmailFocusLost
        // TODO add your handling code here:
        activateLabelFocusLost(JtfRegisterEmail.getText().trim(), ErrorEmail);
    }//GEN-LAST:event_JtfRegisterEmailFocusLost

    private void JtfRegisterCellFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JtfRegisterCellFocusLost
        // TODO add your handling code here:
        activateLabelFocusLost(JtfRegisterCell.getText().trim(), ErrorCell);
    }//GEN-LAST:event_JtfRegisterCellFocusLost

    private void JtfRegisterPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JtfRegisterPasswordFocusLost
        // TODO add your handling code here:
        activateLabelFocusLost(new String(JtfRegisterPassword.getPassword()).trim(), ErrorPassword);
    }//GEN-LAST:event_JtfRegisterPasswordFocusLost

    private void JtfRegisterConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JtfRegisterConfirmPasswordFocusLost
        // TODO add your handling code here:

        sPassword = new String(JtfRegisterPassword.getPassword()).trim();
        sConfirmPassword = new String(JtfRegisterConfirmPassword.getPassword()).trim();
        if (sPassword.equals(sConfirmPassword)) {
            ContraseñasIncorrectas.setVisible(false);
        } else {
            ContraseñasIncorrectas.setVisible(true);
        }
        activateLabelFocusLost(sConfirmPassword, ErrorConfirmPassword);
    }//GEN-LAST:event_JtfRegisterConfirmPasswordFocusLost

    private void JtfRegisterNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfRegisterNameKeyTyped
        // TODO add your handling code here:
        validateCharacters(evt);

    }//GEN-LAST:event_JtfRegisterNameKeyTyped

    private void JtfRegisterLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfRegisterLastNameKeyTyped
        // TODO add your handling code here:
        validateCharacters(evt);
    }//GEN-LAST:event_JtfRegisterLastNameKeyTyped

    private void JtfRegisterCellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfRegisterCellKeyTyped
        // TODO add your handling code here:
        validateNumbers(evt);
    }//GEN-LAST:event_JtfRegisterCellKeyTyped

    private void JtfRegisterCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfRegisterCellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfRegisterCellActionPerformed

    private void JtfRegisterEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfRegisterEmailKeyReleased
        // TODO add your handling code here:
        if (validateEmail(JtfRegisterEmail.getText())) {
            EmailInvalido.setVisible(false);
            EmailValido.setVisible(true);
        } else {
            EmailValido.setVisible(false);
            EmailInvalido.setVisible(true);
        }
    }//GEN-LAST:event_JtfRegisterEmailKeyReleased

    private void JtfRegisterConfirmPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfRegisterConfirmPasswordKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_JtfRegisterConfirmPasswordKeyTyped

    private void JtfRegisterEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfRegisterEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfRegisterEmailKeyTyped

    public void getData() {
        sName = JtfRegisterName.getText().trim();
        sLastName = JtfRegisterLastName.getText().trim();
        sPassword = new String(JtfRegisterPassword.getPassword()).trim();
        sConfirmPassword = new String(JtfRegisterConfirmPassword.getPassword()).trim();
        sEmail = JtfRegisterEmail.getText().trim();
        sCell = JtfRegisterCell.getText().trim();
    }

    public void seteoLabel(boolean b) {

        ErrorName.setVisible(b);
        ErrorLastName.setVisible(b);
        ErrorEmail.setVisible(b);
        ErrorPassword.setVisible(b);
        ErrorConfirmPassword.setVisible(b);
        ErrorCell.setVisible(b);
    }

    public void seteoJtextField() {
        JtfRegisterName.setText("");
        JtfRegisterLastName.setText("");
        JtfRegisterEmail.setText("");
        JtfRegisterPassword.setText("");
        JtfRegisterConfirmPassword.setText("");
        JtfRegisterCell.setText("");
    }

    public void activateLabels(boolean b, int n) {
        switch (n) {
            case 0:
                ErrorName.setVisible(b);
                break;
            case 1:
                ErrorLastName.setVisible(b);
                break;
            case 2:
                ErrorEmail.setVisible(b);
                break;
            case 3:
                ErrorPassword.setVisible(b);
                break;
            case 4:
                ErrorConfirmPassword.setVisible(b);
                break;
            case 5:
                ErrorCell.setVisible(b);
                break;

        }
    }

    public boolean thereEmptyFields() {

        String data[] = new String[6];
        boolean thereAre = false;
        data[0] = sName;
        data[1] = sLastName;
        data[2] = sEmail;
        data[3] = sPassword;
        data[4] = sConfirmPassword;
        data[5] = sCell;

        for (int i = 0; i < 6; i++) {
            if (data[i].isEmpty()) {
                thereAre = true;
                activateLabels(true, i);
            }
        }
        return thereAre;
    }

    public void activateLabelFocusLost(String s, JLabel label) {
        if (s.isEmpty()) {
            label.setVisible(true);
        } else {
            label.setVisible(false);
        }
    }

    public void validateCharacters(KeyEvent evt) {

        char c = evt.getKeyChar();

        if (!(Character.isLetter(c) || c == 32 || c == 8)) {
            evt.consume();

        } else {
            System.out.println(c);
        }
    }

    public void validateNumbers(KeyEvent evt) {
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            evt.consume();
        } else {
            System.out.println(c);
        }
    }

    public boolean validateEmail(String s) {
        Pattern pat = Pattern.compile("(\\W|^)[\\w.\\-]{0,25}@(hotmail|gmail||outlook)\\.com(\\W|$)");
        Matcher mat = pat.matcher(s);
        if (mat.find()) {
            return true;
        } else {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegisterBack;
    private javax.swing.JButton BtnRegisterSucces;
    private javax.swing.JLabel ContraseñasIncorrectas;
    private javax.swing.JLabel EmailInvalido;
    private javax.swing.JLabel EmailValido;
    private javax.swing.JLabel ErrorCell;
    private javax.swing.JLabel ErrorConfirmPassword;
    private javax.swing.JLabel ErrorEmail;
    private javax.swing.JLabel ErrorLastName;
    private javax.swing.JLabel ErrorName;
    private javax.swing.JLabel ErrorPassword;
    private javax.swing.JTextField JtfRegisterCell;
    private javax.swing.JPasswordField JtfRegisterConfirmPassword;
    private javax.swing.JTextField JtfRegisterEmail;
    private javax.swing.JTextField JtfRegisterLastName;
    private javax.swing.JTextField JtfRegisterName;
    private javax.swing.JPasswordField JtfRegisterPassword;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
