/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Externos.CambiarPanel;
import Externos.Correo;
import Objetos.ObAn;
import Vista.RestablecerContraseña;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Restablecer2 extends javax.swing.JPanel {

    public Restablecer2() {
        initComponents();
        JlabelEmail.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlabelEmail = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JtextFieldCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlabelEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JlabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        add(JlabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 430, 30));

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 150, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listoCodigo-1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listoCodigo-2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 336, 345, 47));

        JtextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        JtextFieldCodigo.setBorder(null);
        add(JtextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 281, 320, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TarjetaRecuperacion2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String codigo = JtextFieldCodigo.getText();
        if (codigo.equals("")) {
            //JOptionPane.showMessageDialog(null, "Ingresa el codigo.");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/IngresaElCodigo.png"));
            ObAn.popUpErrorPlantilla.setVisible(true);
        } else {
            if (codigo.equalsIgnoreCase(ObAn.restablecer.codigo)) { //ObAn.restablecer.codigo esto va dentro del parentesis.
                new CambiarPanel(ObAn.vd2.jPanel1, ObAn.restablecer3);
                ObAn.restablecer.codigo = "";
            } else {
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/CodigoInvalido.png"));
                ObAn.popUpErrorPlantilla.setVisible(true);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ObAn.restablecer.generarEmail();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void seteoGlobal() {
        JtextFieldCodigo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JlabelEmail;
    private javax.swing.JTextField JtextFieldCodigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
