/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Externos.CambiarPanel;
import Externos.Correo;
import Objetos.ObAn;
import PopUps.VentanaDialogo2;
import Vista.RestablecerContraseña;
import bijou.Bijou;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Restablecer extends javax.swing.JPanel {

    /**
     * Creates new form Restablecer
     */
    Correo mensaje;
    public String email;
    public static String codigo = " ";

    public Restablecer() {
        initComponents();
        ObAn.placeHolder("Correo Electronico", JtextFieldEmail);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        JtextFieldEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviarCodigo-1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviarCodigo-2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 390, 245, 57));

        JtextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        JtextFieldEmail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        JtextFieldEmail.setForeground(new java.awt.Color(196, 196, 196));
        JtextFieldEmail.setBorder(null);
        add(JtextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 321, 340, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TarjetaRecuperacion1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //prueba nadamas

        email = JtextFieldEmail.getText().trim();
        if (email.equals("")) {
            //JOptionPane.showMessageDialog(null, "Ingresa tu email.");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/IngresaTuEmail.png"));
            ObAn.popUpErrorPlantilla.setVisible(true);

        } else {
            if (new SQL.Conexion().verificarExistenciaUsuario(email)) {

                //Primero genero el email y se lo mando al usuario.
                generarEmail();
                //Muestro un mensaje para q se quede mas tranquilo
                //JOptionPane.showMessageDialog(null, "Listo, revisa tu correo.");
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ListoRevisaTuCorreo.png"));
                ObAn.popUpErrorPlantilla.setVisible(true);
                //Coloco su email en la siguiente interfaz.
                ObAn.restablecer2.JlabelEmail.setText(email);
                //Cambio a la siguiente interfaz
                new CambiarPanel(ObAn.vd2.jPanel1, ObAn.restablecer2);
                //¿QUE?
                System.out.println("SIUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.");

            } else {
                //JOptionPane.showMessageDialog(null, "El email que ingreso no se encuentra registrado");
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/EmailNoRegistrado.png"));
                ObAn.popUpErrorPlantilla.setVisible(true);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public void generarEmail() {
        codigo = UUID.randomUUID().toString().toUpperCase().substring(0, 6);
        mensaje = new Correo(email, "Restablece tu contraseña de Bijou", "¡Sera "
                + "sencillo solo escribe el siguiente codigo:" + codigo);
        mensaje.enviarEmail();

    }

    public void seteoGlobal() {
        JtextFieldEmail.setText("");
    }

    public String getEmail() {
        return email;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtextFieldEmail;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
