/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Externos.Algoritmos;
import Externos.CambiarPanel;
import Objetos.ObAn;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Restablecer3 extends javax.swing.JPanel {

    /**
     * Creates new form Restablecer2
     */
    String nuevaContraseña;
    String confirmarNuevaContraseña;
    Algoritmos algoritmos;

    public Restablecer3() {
        initComponents();
        ObAn.placeHolder("Nueva contraseña", JtextFieldNuevaContraseña);
        ObAn.placeHolder("Confirmar nueva contraseña", JtextFieldRepetirNuevaContraseña);
        JlabelContraseñaInvalida.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JtextFieldRepetirNuevaContraseña = new javax.swing.JPasswordField();
        JtextFieldNuevaContraseña = new javax.swing.JPasswordField();
        JlabelArroba = new javax.swing.JLabel();
        JlabelMayusculas = new javax.swing.JLabel();
        JlabelNumeros = new javax.swing.JLabel();
        JlabelSimbolos = new javax.swing.JLabel();
        JlabelContraseñaInvalida = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        BtnEstablecerContraseña = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JtextFieldRepetirNuevaContraseña.setBackground(new java.awt.Color(255, 255, 255));
        JtextFieldRepetirNuevaContraseña.setBorder(null);
        add(JtextFieldRepetirNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 350, 400, 25));

        JtextFieldNuevaContraseña.setBackground(new java.awt.Color(255, 255, 255));
        JtextFieldNuevaContraseña.setBorder(null);
        JtextFieldNuevaContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtextFieldNuevaContraseñaKeyReleased(evt);
            }
        });
        add(JtextFieldNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 171, 400, 25));
        add(JlabelArroba, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 257, 24, 23));
        add(JlabelMayusculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 257, 24, 23));
        add(JlabelNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 257, 24, 23));
        add(JlabelSimbolos, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 257, 24, 23));

        JlabelContraseñaInvalida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JlabelContraseñaInvalida.setForeground(new java.awt.Color(255, 64, 64));
        JlabelContraseñaInvalida.setText("Ingresa al menos 8 caracteres");
        add(JlabelContraseñaInvalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 126, -1, -1));

        BtnVolver.setBorder(null);
        BtnVolver.setContentAreaFilled(false);
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 300, 20));

        BtnEstablecerContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/establecerContraseña-1.png"))); // NOI18N
        BtnEstablecerContraseña.setBorder(null);
        BtnEstablecerContraseña.setContentAreaFilled(false);
        BtnEstablecerContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEstablecerContraseña.setFocusPainted(false);
        BtnEstablecerContraseña.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/establecerContraseña-2.png"))); // NOI18N
        BtnEstablecerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstablecerContraseñaActionPerformed(evt);
            }
        });
        add(BtnEstablecerContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 404, 375, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TarjetaRecuperacion3.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void JtextFieldNuevaContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextFieldNuevaContraseñaKeyReleased
        // TODO add your handling code here:

        //3 AM, no se como funciona, luego lo comento.
        obtenerContraseñas();
        algoritmos = new Algoritmos(nuevaContraseña);

        algoritmos.analizarContraseña();

        if (algoritmos.isMin8caracteres()) {
            JlabelContraseñaInvalida.setVisible(false);
        } else {
            JlabelContraseñaInvalida.setVisible(true);
        }
        if (algoritmos.isMin1signo()) {
            JlabelSimbolos.setIcon(new ImageIcon(getClass().
                    getResource("/Imagenes/aceptarFinal.png")));
        } else {
            JlabelSimbolos.setIcon(new ImageIcon(getClass().
                    getResource("/Imagenes/cancelarFinal.png")));
        }

        if (algoritmos.isMin1numero()) {
            JlabelNumeros.setIcon(new ImageIcon(getClass().
                    getResource("/Imagenes/aceptarFinal.png")));
        } else {
            JlabelNumeros.setIcon(new ImageIcon(getClass().
                    getResource("/Imagenes/cancelarFinal.png")));
        }

        if (algoritmos.isMin1mayuscula()) {
            JlabelMayusculas.setIcon(new ImageIcon(getClass().
                    getResource("/Imagenes/aceptarFinal.png")));
        } else {
            JlabelMayusculas.setIcon(new ImageIcon(getClass().
                    getResource("/Imagenes/cancelarFinal.png")));
        }

        if (algoritmos.isMin1arroba()) {
            JlabelArroba.setIcon(new ImageIcon(getClass().
                    getResource("/Imagenes/aceptarFinal.png")));
        } else {
            JlabelArroba.setIcon(new ImageIcon(getClass().
                    getResource("/Imagenes/cancelarFinal.png")));
        }


    }//GEN-LAST:event_JtextFieldNuevaContraseñaKeyReleased

    private void BtnEstablecerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstablecerContraseñaActionPerformed
        // TODO add your handling code here:

        obtenerContraseñas();
        if (algoritmos.isMin8caracteres()) {
            if (algoritmos.isMin1signo()) {
                if (algoritmos.isMin1numero()) {
                    if (algoritmos.isMin1mayuscula()) {
                        if (algoritmos.isMin1arroba()) {
                            if (confirmarNuevaContraseña.equals(nuevaContraseña)) {

                                //JOptionPane.showMessageDialog(null, "Contraseña actualizada");
                                new SQL.Conexion().actualizarContraseña(ObAn.restablecer.email, nuevaContraseña);

                                seteoGlobal();
                                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ContraseñaActualizada.png"));
                                ObAn.popUpErrorPlantilla.setVisible(true);

                                //Aqui podriamos meter un POPUP.
                                ObAn.vd2.dispose();
                                new CambiarPanel(ObAn.vd2.jPanel1, ObAn.restablecer);

                            } else {
                                //JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
                                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/LasContraseñasNo.png"));
                                ObAn.popUpErrorPlantilla.setVisible(true);
                            }
                        } else {
                            //JOptionPane.showMessageDialog(null, "Coloca al menos 1 arroba en tu contraseña.");
                            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ColocaAlMenos1Arroba.png"));
                                ObAn.popUpErrorPlantilla.setVisible(true);
                        }
                    } else {
                        //JOptionPane.showMessageDialog(null, "Coloca al menos 1 mayuscula en tu contraseña.");
                        ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ColocaAlMenos1Mayuscula.png"));
                                ObAn.popUpErrorPlantilla.setVisible(true);
                    }
                } else {
                    //JOptionPane.showMessageDialog(null, "Coloca al menos 1 numero en tu contraseña.");
                    ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ColocaAlMenos1Numero.png"));
                                ObAn.popUpErrorPlantilla.setVisible(true);
                }
            } else {
                //JOptionPane.showMessageDialog(null, "Coloca al menos 1 signo en tu contraseña.");
                ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/ColocaAlMenos1Signo.png"));
                                ObAn.popUpErrorPlantilla.setVisible(true);
            }
        } else {
            //JOptionPane.showMessageDialog(null, "Tu contraseña debe de ser de al menos 8 caracteres.");
            ObAn.popUpErrorPanel.jLabel1.setIcon(new ImageIcon("src/Imagenes/TuContraseñaDebe.png"));
                                ObAn.popUpErrorPlantilla.setVisible(true);
        }


    }//GEN-LAST:event_BtnEstablecerContraseñaActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        //Esto es opcional
        seteoGlobal();
        //Aqui podriamos meter un POPUP.
        ObAn.vd2.dispose();
        new CambiarPanel(ObAn.vd2.jPanel1, ObAn.restablecer);

    }//GEN-LAST:event_BtnVolverActionPerformed
    public void seteoGlobal() {
        JtextFieldNuevaContraseña.setText("");
        JtextFieldRepetirNuevaContraseña.setText("");
        JlabelArroba.setIcon(null);
        JlabelMayusculas.setIcon(null);
        JlabelNumeros.setIcon(null);
        JlabelSimbolos.setIcon(null);
        JlabelContraseñaInvalida.setVisible(false);
    }

    public void obtenerContraseñas() {
        nuevaContraseña = new String(JtextFieldNuevaContraseña.getPassword()).trim();
        confirmarNuevaContraseña = new String(JtextFieldRepetirNuevaContraseña.getPassword()).trim();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEstablecerContraseña;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel JlabelArroba;
    private javax.swing.JLabel JlabelContraseñaInvalida;
    private javax.swing.JLabel JlabelMayusculas;
    private javax.swing.JLabel JlabelNumeros;
    private javax.swing.JLabel JlabelSimbolos;
    private javax.swing.JPasswordField JtextFieldNuevaContraseña;
    private javax.swing.JPasswordField JtextFieldRepetirNuevaContraseña;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
