/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Externos.CambiarPanel;
import Externos.Correo;
import Objetos.Carrito;
import Objetos.ObAn;
import Vista.Plantilla;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.activation.FileDataSource;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class SeleccionarTarjeta extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionarMetodoPago2
     */
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    String fechaVenta;
    Correo mensaje;
    String email;
    ArrayList<Carrito> datosPDF;
    Document documento;
    File file;
    FileDataSource fdatasource;

    public SeleccionarTarjeta() {
        initComponents();
        visibleTarjeta3(false);
        visibleTarjeta2(false);
        visibleTarjeta1(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vencimientoTarjeta3 = new javax.swing.JLabel();
        tipoTarjeta3 = new javax.swing.JLabel();
        tituloTarjeta3 = new javax.swing.JLabel();
        vencimientoTarjeta2 = new javax.swing.JLabel();
        tipoTarjeta2 = new javax.swing.JLabel();
        tituloTarjeta2 = new javax.swing.JLabel();
        vencimientoTarjeta1 = new javax.swing.JLabel();
        tipoTarjeta1 = new javax.swing.JLabel();
        tituloTarjeta1 = new javax.swing.JLabel();
        btnTarjeta2 = new javax.swing.JButton();
        btnTarjeta3 = new javax.swing.JButton();
        btnTarjeta1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vencimientoTarjeta3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        vencimientoTarjeta3.setForeground(new java.awt.Color(153, 153, 153));
        vencimientoTarjeta3.setText("Vencimiento: ");
        add(vencimientoTarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 320, -1));

        tipoTarjeta3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipoTarjeta3.setForeground(new java.awt.Color(153, 153, 153));
        tipoTarjeta3.setText("Visa");
        add(tipoTarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 320, -1));

        tituloTarjeta3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloTarjeta3.setForeground(new java.awt.Color(102, 102, 102));
        tituloTarjeta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(tituloTarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 470, 30));

        vencimientoTarjeta2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        vencimientoTarjeta2.setForeground(new java.awt.Color(153, 153, 153));
        vencimientoTarjeta2.setText("Vencimiento: ");
        add(vencimientoTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 320, -1));

        tipoTarjeta2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipoTarjeta2.setForeground(new java.awt.Color(153, 153, 153));
        tipoTarjeta2.setText("Visa");
        add(tipoTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 320, -1));

        tituloTarjeta2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloTarjeta2.setForeground(new java.awt.Color(102, 102, 102));
        tituloTarjeta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(tituloTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 470, 30));

        vencimientoTarjeta1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        vencimientoTarjeta1.setForeground(new java.awt.Color(153, 153, 153));
        vencimientoTarjeta1.setText("Vencimiento: ");
        add(vencimientoTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 177, 320, -1));

        tipoTarjeta1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipoTarjeta1.setForeground(new java.awt.Color(153, 153, 153));
        tipoTarjeta1.setText("Visa");
        add(tipoTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 152, 320, -1));

        tituloTarjeta1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloTarjeta1.setForeground(new java.awt.Color(102, 102, 102));
        tituloTarjeta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(tituloTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 470, 30));

        btnTarjeta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonVisa.png"))); // NOI18N
        btnTarjeta2.setBorder(null);
        btnTarjeta2.setContentAreaFilled(false);
        btnTarjeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjeta2ActionPerformed(evt);
            }
        });
        add(btnTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 490, 100));

        btnTarjeta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonVisa.png"))); // NOI18N
        btnTarjeta3.setBorder(null);
        btnTarjeta3.setContentAreaFilled(false);
        btnTarjeta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjeta3ActionPerformed(evt);
            }
        });
        add(btnTarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 490, 100));

        btnTarjeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonVisa.png"))); // NOI18N
        btnTarjeta1.setBorder(null);
        btnTarjeta1.setContentAreaFilled(false);
        btnTarjeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjeta1ActionPerformed(evt);
            }
        });
        add(btnTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 490, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TarjetasRegistradas.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjeta1ActionPerformed
        // TODO add your handling code here:
        pagar();
        generarPDF();

    }//GEN-LAST:event_btnTarjeta1ActionPerformed

    private void btnTarjeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjeta2ActionPerformed
        // TODO add your handling code here:}
        pagar();
        generarPDF();
    }//GEN-LAST:event_btnTarjeta2ActionPerformed

    private void btnTarjeta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjeta3ActionPerformed
        // TODO add your handling code here:
        pagar();
        generarPDF();
    }//GEN-LAST:event_btnTarjeta3ActionPerformed

    public void visibleTarjeta2(boolean estado) {
        btnTarjeta2.setVisible(estado);
        tituloTarjeta2.setVisible(estado);
        tipoTarjeta2.setVisible(estado);
        vencimientoTarjeta2.setVisible(estado);
    }

    public void visibleTarjeta1(boolean estado) {
        btnTarjeta1.setVisible(estado);
        tituloTarjeta1.setVisible(estado);
        tipoTarjeta1.setVisible(estado);
        vencimientoTarjeta1.setVisible(estado);
    }

    public void visibleTarjeta3(boolean estado) {
        btnTarjeta3.setVisible(estado);
        tituloTarjeta3.setVisible(estado);
        tipoTarjeta3.setVisible(estado);
        vencimientoTarjeta3.setVisible(estado);
    }

    public void pagar() {
       
        for (int i = 0; i < ObAn.user.carrito.size(); i++) {
            fechaVenta = dtf.format(LocalDateTime.now());
            new SQL.Conexion().agregarVenta(ObAn.user.carrito.get(i).getUnidades(),fechaVenta, ObAn.user.carrito.get(i).getPrecioVenta(), ObAn.user.carrito.get(i).getIdProducto(), ObAn.usuario.getIdUsuario());
            //La siguiente linea es por si las dudas, para dejar la fecha en blanco, aun asi yo creo que se sobreescribe pero weno.
            fechaVenta = "";
        }
    }

    public void generarPDF() {
        int totalProductos = 0;
        String productos = "";
        datosPDF = new SQL.Conexion().obtenerDatosPDF(ObAn.usuario.getIdUsuario(), ObAn.user.carrito.size());

        //Calculando el total de los productos
        for (int i = 0; i < datosPDF.size(); i++) {
            totalProductos += datosPDF.get(i).getPrecioVenta();
            System.out.println(datosPDF.get(i).getDescripcion());
            productos += "Descripcion: " + datosPDF.get(i).getDescripcion() + " - Unidades: " + datosPDF.get(i).getUnidades() + " - Precio unitario = $" + datosPDF.get(i).getPrecio() + " - Precio total = $" + datosPDF.get(i).getPrecioVenta() + ".\n";
        }

        documento = new Document();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte.pdf"));

            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.setFont(FontFactory.getFont("Tahoma", 20, Font.BOLD, BaseColor.DARK_GRAY));
            parrafo.add("\nU N I F O R M E S  B I J O U  \n\n");

            parrafo.setAlignment(Paragraph.ALIGN_LEFT);
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Nombre: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(ObAn.usuario.getNombre() + " " + ObAn.usuario.getApellidos() + "\n\n");
            /*
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Telefono: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(labelTelefono.getText() + "\n\n");
             */

            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Correo: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(ObAn.usuario.getEmail() + "\n\n");

            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Celular ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(ObAn.usuario.getCelular() + "\n\n");
            /*
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Ciudad: ");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(labelCiudad.getText() + "\n\n");*/

            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Productos: \n" + "Total productos = $" + totalProductos + "\n");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.ITALIC, BaseColor.BLACK));
            parrafo.add(productos + "\n");

            Image imagen = Image.getInstance("src/imagenes/Cabecera.png");
            imagen.scaleToFit(2480, 100);
            imagen.setAlignment(Chunk.ALIGN_CENTER);

            Image imagen2 = Image.getInstance("src/imagenes/Pie.png");
            imagen2.scaleToFit(2480, 100);
            imagen2.setAlignment(Chunk.ALIGN_CENTER);

            documento.open();
            documento.add(imagen);
            documento.add(parrafo);
            documento.add(imagen2);
            documento.close();

            file = new File("C:/Users/PC/Desktop/Reporte.pdf");
            fdatasource = new FileDataSource(file);

            email = ObAn.usuario.getEmail();
            mensaje = new Correo(email, "Detalles de tu compra en BIJOU", "Te adjuntamos los detalles de tu compra, ¡revisalos!");
            mensaje.enviarCorreoPDF(fdatasource, "Reporte.pdf");

        } catch (Exception e) {

        }
        reflejarEnStock();
        //JOptionPane.showMessageDialog(null, "PDF generado con exito.");
        ObAn.user.carrito.clear();
        ObAn.vd2.jButton2.setVisible(false);
        new CambiarPanel(ObAn.vd2.jPanel1, ObAn.agradecimiento);

    }

    public void reflejarEnStock() {
        int cantidadStockActual;
        int cantidadArticulos;
        int cantidadStockUPDATE;
        for (int i = 0; i < ObAn.user.carrito.size(); i++) {
            cantidadStockActual = new SQL.Conexion().obtenerStock(ObAn.user.carrito.get(i).getIdProducto());
            cantidadArticulos = ObAn.user.carrito.get(i).getUnidades();
            cantidadStockUPDATE = cantidadStockActual - cantidadArticulos;
            new SQL.Conexion().actualizarStock(ObAn.user.carrito.get(i).getIdProducto(), cantidadStockUPDATE);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnTarjeta1;
    public javax.swing.JButton btnTarjeta2;
    public javax.swing.JButton btnTarjeta3;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel tipoTarjeta1;
    public javax.swing.JLabel tipoTarjeta2;
    public javax.swing.JLabel tipoTarjeta3;
    public javax.swing.JLabel tituloTarjeta1;
    public javax.swing.JLabel tituloTarjeta2;
    public javax.swing.JLabel tituloTarjeta3;
    public javax.swing.JLabel vencimientoTarjeta1;
    public javax.swing.JLabel vencimientoTarjeta2;
    public javax.swing.JLabel vencimientoTarjeta3;
    // End of variables declaration//GEN-END:variables
}
