/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Externos.CambiarPanel;
import Objetos.ObAn;
import Objetos.TarjetasDebito;
import java.util.ArrayList;

/**
 *
 * @author PC
 */
public class SeleccionarMetodoPago extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionarMetodoPago
     */
    
    ArrayList<TarjetasDebito> listaTarjetas;
    
    public SeleccionarMetodoPago() {
        initComponents();
        botonVerMetodoPago.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAgregarMetodoPago = new javax.swing.JButton();
        botonVerMetodoPago = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAgregarMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarUnNuevoMetodo-1.png"))); // NOI18N
        botonAgregarMetodoPago.setBorder(null);
        botonAgregarMetodoPago.setContentAreaFilled(false);
        botonAgregarMetodoPago.setFocusPainted(false);
        botonAgregarMetodoPago.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarUnNuevoMetodo-2.png"))); // NOI18N
        botonAgregarMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarMetodoPagoActionPerformed(evt);
            }
        });
        add(botonAgregarMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 501, 85));

        botonVerMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TarjetasGuardadas-1.png"))); // NOI18N
        botonVerMetodoPago.setBorder(null);
        botonVerMetodoPago.setContentAreaFilled(false);
        botonVerMetodoPago.setFocusPainted(false);
        botonVerMetodoPago.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TarjetasGuardadas-2.png"))); // NOI18N
        botonVerMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMetodoPagoActionPerformed(evt);
            }
        });
        add(botonVerMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 501, 85));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SeleccionarMetodoDePago.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarMetodoPagoActionPerformed
        // TODO add your handling code here:
            new CambiarPanel(ObAn.vd2.jPanel1, ObAn.registroTarjeta);
    }//GEN-LAST:event_botonAgregarMetodoPagoActionPerformed

    private void botonVerMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMetodoPagoActionPerformed
        // TODO add your handling code here:
        listaTarjetas = new SQL.Conexion().obtenerRegistroTarjetas(ObAn.usuario.getIdUsuario());
        mostrarTarjetas();
        new CambiarPanel(ObAn.vd2.jPanel1, ObAn.seleccionarMetodoPago2);
        
    }//GEN-LAST:event_botonVerMetodoPagoActionPerformed

        public void mostrarTarjetas(){
            String numeroTarjeta;
            String terminacionTarjeta;
            String fechaVencimiento;
            if(listaTarjetas.size() == 1){
                ObAn.seleccionarMetodoPago2.visibleTarjeta2(true);
                numeroTarjeta = listaTarjetas.get(0).getNumeroTarjeta();
                terminacionTarjeta = numeroTarjeta.substring(numeroTarjeta.length()-4);
                ObAn.seleccionarMetodoPago2.tituloTarjeta2.setText("Terminada en " + terminacionTarjeta);
                fechaVencimiento = listaTarjetas.get(0).getFechaExpiracion();
                ObAn.seleccionarMetodoPago2.vencimientoTarjeta2.setText("Vencimiento: " + fechaVencimiento);
            }
            else if(listaTarjetas.size() == 2){
                //Lo siguiente no es factible, pero tengo sueño
                //Activamos tarjeta 1
                ObAn.seleccionarMetodoPago2.visibleTarjeta2(true);
                numeroTarjeta = listaTarjetas.get(0).getNumeroTarjeta();
                terminacionTarjeta = numeroTarjeta.substring(numeroTarjeta.length()-4);
                ObAn.seleccionarMetodoPago2.tituloTarjeta2.setText("Terminada en " + terminacionTarjeta);
                fechaVencimiento = listaTarjetas.get(0).getFechaExpiracion();
                ObAn.seleccionarMetodoPago2.vencimientoTarjeta2.setText("Vencimiento: " + fechaVencimiento);
                
                //Activamos tarjeta 2
                ObAn.seleccionarMetodoPago2.visibleTarjeta1(true);
                numeroTarjeta = listaTarjetas.get(1).getNumeroTarjeta();
                terminacionTarjeta = numeroTarjeta.substring(numeroTarjeta.length()-4);
                ObAn.seleccionarMetodoPago2.tituloTarjeta1.setText("Terminada en " + terminacionTarjeta);
                fechaVencimiento = listaTarjetas.get(1).getFechaExpiracion();
                ObAn.seleccionarMetodoPago2.vencimientoTarjeta1.setText("Vencimiento: " + fechaVencimiento);
            }
            
            else if(listaTarjetas.size() == 3){
                //Lo siguiente no es factible, pero tengo sueño
                //Activamos tarjeta 1
                ObAn.seleccionarMetodoPago2.visibleTarjeta2(true);
                numeroTarjeta = listaTarjetas.get(0).getNumeroTarjeta();
                terminacionTarjeta = numeroTarjeta.substring(numeroTarjeta.length()-4);
                ObAn.seleccionarMetodoPago2.tituloTarjeta2.setText("Terminada en " + terminacionTarjeta);
                fechaVencimiento = listaTarjetas.get(0).getFechaExpiracion();
                ObAn.seleccionarMetodoPago2.vencimientoTarjeta2.setText("Vencimiento: " + fechaVencimiento);
                
                //Activamos tarjeta 2
                ObAn.seleccionarMetodoPago2.visibleTarjeta1(true);
                numeroTarjeta = listaTarjetas.get(1).getNumeroTarjeta();
                terminacionTarjeta = numeroTarjeta.substring(numeroTarjeta.length()-4);
                ObAn.seleccionarMetodoPago2.tituloTarjeta1.setText("Terminada en " + terminacionTarjeta);
                fechaVencimiento = listaTarjetas.get(1).getFechaExpiracion();
                ObAn.seleccionarMetodoPago2.vencimientoTarjeta1.setText("Vencimiento: " + fechaVencimiento);
                
                //Activamos tarjeta 3
                ObAn.seleccionarMetodoPago2.visibleTarjeta3(true);
                numeroTarjeta = listaTarjetas.get(2).getNumeroTarjeta();
                terminacionTarjeta = numeroTarjeta.substring(numeroTarjeta.length()-4);
                ObAn.seleccionarMetodoPago2.tituloTarjeta3.setText("Terminada en " + terminacionTarjeta);
                fechaVencimiento = listaTarjetas.get(2).getFechaExpiracion();
                ObAn.seleccionarMetodoPago2.vencimientoTarjeta3.setText("Vencimiento: " + fechaVencimiento);
                
            }
        }
        
        
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarMetodoPago;
    public javax.swing.JButton botonVerMetodoPago;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
